// tests/cli/emit.test.ts
//
// GitOps PR1 (`adapter-k8s emit`, cutover.mode: none). The review-critical surface is the
// previous-build/first-deploy input semantics — N20's new front door — so those tests come
// first and are exhaustive about the fail-closed distinctions ("no prior bundle" ≠ "first
// deploy"; "corrupt prior bundle" ≠ "no prior bundle"). Bundle assembly runs against a real
// temp directory (real fs, like state.test.ts) with only subprocess seams mocked.
import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import path from "node:path";
import os from "node:os";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";

vi.mock("../../src/cli/exec.js");
vi.mock("../../src/pipeline/digests.js", async (importOriginal) => {
  const actual = await importOriginal<typeof import("../../src/pipeline/digests.js")>();
  return { ...actual, resolveDeployImageDigests: vi.fn() };
});

import { execCapture, execOrThrow } from "../../src/cli/exec.js";
import { resolveDeployImageDigests } from "../../src/pipeline/digests.js";
import {
  EMIT_VERSION,
  parseChartValues,
  readPriorBundleMetadata,
  renderBundleReadme,
  resolvePreviousBuildId,
  runEmit,
  type EmitMetadata,
} from "../../src/cli/emit.js";
import { internalSecretName } from "../../src/emit/templates/internal-secret.js";

const DIGEST_SSR = `sha256:${"a".repeat(64)}`;
const DIGEST_ROUTING = `sha256:${"b".repeat(64)}`;
const REGISTRY = "us-central1-docker.pkg.dev/my-project/nextjs";
const RELEASE = "my-app";
const BUILD = "build2abc";
const PREV_BUILD = "build1xyz";

let projectDir: string;

function chartValuesFixture(buildId: string): string {
  const values = {
    global: {
      targetArchitecture: "amd64",
      image: { registry: REGISTRY, repository: "nextjs-app", tag: buildId },
      networkPolicy: { podCidrs: [], nodeCidrs: [], strict: true },
    },
    pools: {
      ssr: {
        image: { repository: "nextjs-app-ssr", digest: "" },
        replicas: { min: 1, max: 3, targetCPU: 80 },
      },
    },
    routingService: { image: { digest: "" } },
    gateway: {},
    build: { id: buildId, nextVersion: "16.0.0", containerStrategy: "traced-assets" },
    activeBuildId: buildId,
    activeDefaultPool: "ssr",
    poolHealthCheckPath: "/readyz",
  };
  return (
    `# Auto-generated by @next-community/adapter-k8s (provider: gke)\n` +
    `# Build ID: ${buildId}\n# Next.js: 16.0.0\n` +
    JSON.stringify(values, null, 2)
  );
}

function writeFixture(opts?: {
  buildId?: string;
  nodeCidrs?: string[];
  podCidrs?: string[];
  omitValkey?: boolean;
}): void {
  const buildId = opts?.buildId ?? BUILD;
  const outputDir = path.join(projectDir, ".k8s-adapter", "output");
  const chartDir = path.join(outputDir, "chart", "templates");
  mkdirSync(chartDir, { recursive: true });
  writeFileSync(
    path.join(projectDir, ".k8s-adapter", "infrastructure.json"),
    JSON.stringify({ containerRegistry: REGISTRY, namespace: "default" }),
  );
  writeFileSync(
    path.join(outputDir, "build-metadata.json"),
    JSON.stringify({
      buildId,
      nextVersion: "16.0.0",
      provider: "gke",
      namespace: "default",
      containerRegistry: REGISTRY,
      pools: ["ssr"],
      defaultPool: "ssr",
      distDir: ".next",
      containerStrategy: "traced-assets",
      hasMiddleware: true,
      failureModeAllow: false,
      cacheEnabled: false,
      cacheManaged: false,
      incrementalCacheHandler: false,
      ...(opts?.nodeCidrs ? { nodeCidrs: opts.nodeCidrs } : {}),
      ...(opts?.podCidrs ? { podCidrs: opts.podCidrs } : {}),
    }),
  );
  writeFileSync(path.join(outputDir, "chart", "values.yaml"), chartValuesFixture(buildId));
  writeFileSync(path.join(outputDir, "chart", "Chart.yaml"), `apiVersion: v2\nname: ${RELEASE}\n`);
  writeFileSync(
    path.join(chartDir, "internal-secret.yaml"),
    `apiVersion: v1\nkind: Secret\nmetadata:\n  name: ${internalSecretName(RELEASE, buildId)}\nstringData:\n  secret: "hunter2"\n`,
  );
  if (!opts?.omitValkey) {
    writeFileSync(
      path.join(chartDir, "valkey-secret.yaml"),
      `apiVersion: v1\nkind: Secret\nmetadata:\n  name: ${RELEASE}-valkey\nstringData:\n  url: "redis://cache:6379"\n`,
    );
  }
  writeFileSync(
    path.join(chartDir, "ssr-deployment.yaml"),
    "apiVersion: apps/v1\nkind: Deployment\n",
  );
}

function priorBundleFixture(overrides?: Partial<EmitMetadata>): void {
  const bundleDir = path.join(projectDir, ".k8s-adapter", "gitops");
  mkdirSync(bundleDir, { recursive: true });
  writeFileSync(
    path.join(bundleDir, "emit-metadata.json"),
    JSON.stringify({
      emitVersion: EMIT_VERSION,
      buildId: PREV_BUILD,
      previousBuildId: null,
      releaseName: RELEASE,
      namespace: "default",
      registry: REGISTRY,
      digests: {},
      cdnTag: "build-" + "0".repeat(64),
      poolTopology: ["ssr"],
      defaultPool: "ssr",
      targetPlatforms: { [PREV_BUILD]: "linux/amd64" },
      secretsMode: "external",
      ...overrides,
    }),
  );
}

function bundleValues(): Record<string, unknown> {
  return parseChartValues(
    readFileSync(path.join(projectDir, ".k8s-adapter", "gitops", "values", "values.yaml"), "utf-8"),
  ).values;
}

function bundleMetadata(): EmitMetadata {
  return JSON.parse(
    readFileSync(path.join(projectDir, ".k8s-adapter", "gitops", "emit-metadata.json"), "utf-8"),
  );
}

const baseOptions = () => ({
  projectDir,
  releaseName: RELEASE,
  skipBuild: true,
  skipPush: true,
  // Every runEmit test provides CIDRs or opts out explicitly; the dedicated CIDR tests
  // exercise the fail-closed default.
});

beforeEach(() => {
  vi.clearAllMocks();
  projectDir = mkdtempSync(path.join(os.tmpdir(), "adapter-k8s-emit-"));
  vi.mocked(resolveDeployImageDigests).mockResolvedValue({
    ssr: DIGEST_SSR,
    routingService: DIGEST_ROUTING,
  });
  // helm absent by default (probe fails) — the manifests step then records a skip note.
  vi.mocked(execCapture).mockResolvedValue({ exitCode: 1, stdout: "", stderr: "" });
  vi.mocked(execOrThrow).mockResolvedValue(undefined);
});

afterEach(() => {
  rmSync(projectDir, { recursive: true, force: true });
});

describe("previous-build semantics (N20's new front door)", () => {
  it("REFUSES when there is no prior bundle and no explicit flag — never infers first deploy", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await expect(runEmit(baseOptions())).rejects.toThrow(/--first-deploy/);
    await expect(runEmit(baseOptions())).rejects.toThrow(/Refusing to infer a first deploy/);
    // Nothing was written.
    expect(existsSync(path.join(projectDir, ".k8s-adapter", "gitops"))).toBe(false);
  });

  it("--first-deploy renders the selectors at the NEW build", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await runEmit({ ...baseOptions(), firstDeploy: true });
    expect(bundleValues().activeBuildId).toBe(BUILD);
    expect(bundleMetadata().previousBuildId).toBeNull();
  });

  it("--previous-build pins activeBuildId to the SANITIZED previous build (the deploy.ts trick at values-write time)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await runEmit({ ...baseOptions(), previousBuild: "123old" });
    // sanitizeK8sName prefixes ids that start with a digit — byte-identical to the pod label.
    expect(bundleValues().activeBuildId).toBe("b-123old");
    expect(bundleMetadata().previousBuildId).toBe("123old");
  });

  it("reads the previous build from the prior bundle's emit-metadata.json (the normal CI flow)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    priorBundleFixture();
    await runEmit(baseOptions());
    expect(bundleValues().activeBuildId).toBe(PREV_BUILD);
    expect(bundleMetadata().previousBuildId).toBe(PREV_BUILD);
  });

  it("a present-but-corrupt prior bundle THROWS — it is not a first deploy", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    const bundleDir = path.join(projectDir, ".k8s-adapter", "gitops");
    mkdirSync(bundleDir, { recursive: true });
    writeFileSync(path.join(bundleDir, "emit-metadata.json"), "{ truncated");
    await expect(runEmit(baseOptions())).rejects.toThrow(/NOT a first deploy/);
  });

  it("a prior bundle from ANOTHER release is refused, not consumed", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    priorBundleFixture({ releaseName: "other-app" });
    await expect(runEmit(baseOptions())).rejects.toThrow(/emitted for release "other-app"/);
  });

  it("a prior bundle from ANOTHER namespace is refused", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    priorBundleFixture({ namespace: "staging" });
    await expect(runEmit(baseOptions())).rejects.toThrow(/emitted for namespace "staging"/);
  });

  it("a prior bundle with a NEWER emitVersion is refused (unknowable layout)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    priorBundleFixture({ emitVersion: EMIT_VERSION + 1 });
    await expect(runEmit(baseOptions())).rejects.toThrow(/emitVersion/);
  });

  it("--first-deploy with an existing prior bundle contradicts and refuses", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    priorBundleFixture();
    await expect(runEmit({ ...baseOptions(), firstDeploy: true })).rejects.toThrow(
      /prior bundle exists/,
    );
  });

  it("--previous-build and --first-deploy together contradict and refuse", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await expect(
      runEmit({ ...baseOptions(), previousBuild: PREV_BUILD, firstDeploy: true }),
    ).rejects.toThrow(/contradict/);
  });

  it("re-emitting the SAME build reuses the prior bundle's own previousBuildId (idempotent, no N14 trip)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    priorBundleFixture({ buildId: BUILD, previousBuildId: PREV_BUILD });
    await runEmit(baseOptions());
    expect(bundleValues().activeBuildId).toBe(PREV_BUILD);
    expect(bundleMetadata().previousBuildId).toBe(PREV_BUILD);
  });

  it("N14: a previous build IDENTICAL to the new build id is refused (deploymentId signature)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await expect(runEmit({ ...baseOptions(), previousBuild: BUILD })).rejects.toThrow(
      /IDENTICAL to the currently-serving build/,
    );
  });

  it("validates a flag-supplied previous build id at the point of consumption", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await expect(runEmit({ ...baseOptions(), previousBuild: "bad,id\\injection" })).rejects.toThrow(
      /build/i,
    );
  });
});

describe("CIDR config surface (fail-closed, A4 'replaced')", () => {
  it("REFUSES to render strict NetworkPolicies with no configured node CIDRs", async () => {
    writeFixture(); // no nodeCidrs
    await expect(runEmit({ ...baseOptions(), firstDeploy: true })).rejects.toThrow(
      /networkPolicy\.nodeCidrs/,
    );
  });

  it("--allow-no-network-policy renders strict: false instead", async () => {
    writeFixture();
    await runEmit({ ...baseOptions(), firstDeploy: true, allowNoNetworkPolicy: true });
    const global = bundleValues().global as { networkPolicy: Record<string, unknown> };
    expect(global.networkPolicy.strict).toBe(false);
    expect(global.networkPolicy.nodeCidrs).toEqual([]);
  });

  it("pins configured node + pod CIDRs into the bundle values", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16", "10.1.0.0/16"], podCidrs: ["10.8.0.0/14"] });
    await runEmit({ ...baseOptions(), firstDeploy: true });
    const global = bundleValues().global as { networkPolicy: Record<string, unknown> };
    expect(global.networkPolicy.strict).toBe(true);
    expect(global.networkPolicy.nodeCidrs).toEqual(["10.0.0.0/16", "10.1.0.0/16"]);
    expect(global.networkPolicy.podCidrs).toEqual(["10.8.0.0/14"]);
  });

  it("rejects malformed CIDRs from build metadata at the point of consumption", async () => {
    writeFixture({ nodeCidrs: ["not-a-cidr"] });
    await expect(runEmit({ ...baseOptions(), firstDeploy: true })).rejects.toThrow(/invalid CIDR/);
  });
});

describe("secret externalization", () => {
  it("external (default): omits both secret templates and emits the ExternalSecret placeholder", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await runEmit({ ...baseOptions(), firstDeploy: true });
    const templates = path.join(projectDir, ".k8s-adapter", "gitops", "chart", "templates");
    expect(existsSync(path.join(templates, "internal-secret.yaml"))).toBe(false);
    expect(existsSync(path.join(templates, "valkey-secret.yaml"))).toBe(false);
    const external = readFileSync(path.join(templates, "external-secret.yaml"), "utf-8");
    // The names/keys the pods reference, from the same single sources of truth.
    expect(external).toContain(`name: ${internalSecretName(RELEASE, BUILD)}`);
    expect(external).toContain("secretKey: secret");
    expect(external).toContain(`name: ${RELEASE}-valkey`);
    expect(external).toContain("helm.sh/resource-policy: keep");
    // Gated so a bundle without a store renders nothing rather than failing.
    expect(external).toContain("{{- if and .Values.externalSecrets");
    expect(bundleMetadata().secretsMode).toBe("external");
    // The README documents the required Secret names/keys.
    const readme = readFileSync(
      path.join(projectDir, ".k8s-adapter", "gitops", "README.md"),
      "utf-8",
    );
    expect(readme).toContain("Secrets (externalized)");
    expect(readme).toContain(`${RELEASE}-valkey`);
  });

  it("external without a cache: no Valkey ExternalSecret is emitted", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"], omitValkey: true });
    await runEmit({ ...baseOptions(), firstDeploy: true });
    const external = readFileSync(
      path.join(projectDir, ".k8s-adapter", "gitops", "chart", "templates", "external-secret.yaml"),
      "utf-8",
    );
    expect(external).not.toContain(`name: ${RELEASE}-valkey`);
  });

  it("inline keeps the secret templates verbatim and warns loudly", async () => {
    const warn = vi.spyOn(console, "warn").mockImplementation(() => {});
    try {
      writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
      await runEmit({ ...baseOptions(), firstDeploy: true, secrets: "inline" });
      const templates = path.join(projectDir, ".k8s-adapter", "gitops", "chart", "templates");
      expect(readFileSync(path.join(templates, "internal-secret.yaml"), "utf-8")).toContain(
        "hunter2",
      );
      expect(existsSync(path.join(templates, "external-secret.yaml"))).toBe(false);
      expect(warn).toHaveBeenCalledWith(expect.stringContaining("REAL credentials"));
      expect(bundleMetadata().secretsMode).toBe("inline");
    } finally {
      warn.mockRestore();
    }
  });

  it("rejects an unknown secrets mode", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await expect(
      runEmit({ ...baseOptions(), firstDeploy: true, secrets: "sealed" as never }),
    ).rejects.toThrow(/--secrets/);
  });
});

describe("bundle assembly", () => {
  it("pins resolved digests into values (pool + routingService)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await runEmit({ ...baseOptions(), firstDeploy: true });
    const values = bundleValues();
    const pools = values.pools as Record<string, { image: { digest: string } }>;
    expect(pools.ssr!.image.digest).toBe(DIGEST_SSR);
    expect((values.routingService as { image: { digest: string } }).image.digest).toBe(
      DIGEST_ROUTING,
    );
    expect(bundleMetadata().digests).toEqual({
      routingService: DIGEST_ROUTING,
      ssr: DIGEST_SSR,
    });
  });

  it("records the per-bundle facts in emit-metadata.json", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await runEmit({ ...baseOptions(), firstDeploy: true });
    const meta = bundleMetadata();
    expect(meta.emitVersion).toBe(EMIT_VERSION);
    expect(meta.buildId).toBe(BUILD);
    expect(meta.releaseName).toBe(RELEASE);
    expect(meta.namespace).toBe("default");
    expect(meta.registry).toBe(REGISTRY);
    expect(meta.poolTopology).toEqual(["ssr"]);
    expect(meta.defaultPool).toBe("ssr");
    expect(meta.cdnTag).toMatch(/^build-[0-9a-f]{64}$/);
    expect(meta.targetPlatforms).toEqual({ [BUILD]: "linux/amd64" });
  });

  it("skips manifests/all.yaml with a recorded note when helm is unavailable", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await runEmit({ ...baseOptions(), firstDeploy: true });
    expect(
      existsSync(path.join(projectDir, ".k8s-adapter", "gitops", "manifests", "all.yaml")),
    ).toBe(false);
    expect(bundleMetadata().manifests).toMatchObject({ skipped: true });
  });

  it("renders manifests/all.yaml via LOCAL `helm template` when helm is present", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    vi.mocked(execCapture).mockImplementation(async (cmd, args) => {
      if (cmd === "helm" && args[0] === "version") {
        return { exitCode: 0, stdout: "v3.15.0", stderr: "" };
      }
      if (cmd === "helm" && args[0] === "template") {
        return { exitCode: 0, stdout: "kind: Deployment\n", stderr: "" };
      }
      throw new Error(`unexpected exec: ${cmd} ${args.join(" ")}`);
    });
    await runEmit({ ...baseOptions(), firstDeploy: true });
    const all = readFileSync(
      path.join(projectDir, ".k8s-adapter", "gitops", "manifests", "all.yaml"),
      "utf-8",
    );
    expect(all).toBe("kind: Deployment\n");
    expect(bundleMetadata().manifests).toBeUndefined();
    // The template call rendered the BUNDLE chart with the BUNDLE values.
    const templateCall = vi
      .mocked(execCapture)
      .mock.calls.find(([cmd, args]) => cmd === "helm" && args[0] === "template")!;
    expect(templateCall[1]).toContain(path.join(projectDir, ".k8s-adapter", "gitops", "chart"));
    expect(templateCall[1]).toContain(
      path.join(projectDir, ".k8s-adapter", "gitops", "values", "values.yaml"),
    );
  });

  it("a FAILING helm template is a hard error, not a skip — a bundle that cannot render must not be committed", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    vi.mocked(execCapture).mockImplementation(async (cmd, args) => {
      if (cmd === "helm" && args[0] === "version") {
        return { exitCode: 0, stdout: "v3.15.0", stderr: "" };
      }
      return { exitCode: 1, stdout: "", stderr: "Error: template: fail" };
    });
    await expect(runEmit({ ...baseOptions(), firstDeploy: true })).rejects.toThrow(
      /helm template failed/,
    );
  });

  it("NEVER touches a cluster: no kubectl, no gcloud get-credentials, no helm upgrade", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await runEmit({ ...baseOptions(), firstDeploy: true });
    for (const call of [
      ...vi.mocked(execCapture).mock.calls,
      ...vi.mocked(execOrThrow).mock.calls,
    ]) {
      const [cmd, args] = call;
      expect(cmd).not.toBe("kubectl");
      expect(`${cmd} ${(args as string[]).join(" ")}`).not.toMatch(/get-credentials|helm upgrade/);
    }
  });

  it("is byte-deterministic: two emits of the same inputs produce identical bundles", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    const bundleDir = path.join(projectDir, ".k8s-adapter", "gitops");
    const snapshot = (): Record<string, string> => {
      const out: Record<string, string> = {};
      const walk = (dir: string, prefix: string): void => {
        for (const entry of readFileSyncDirents(dir)) {
          const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
          if (entry.isDirectory()) walk(path.join(dir, entry.name), rel);
          else out[rel] = readFileSync(path.join(dir, entry.name), "utf-8");
        }
      };
      walk(bundleDir, "");
      return out;
    };

    await runEmit({ ...baseOptions(), previousBuild: PREV_BUILD });
    const first = snapshot();
    // Second run consumes the FIRST bundle's emit-metadata.json (same build → reuses its
    // previousBuildId), so no flag is needed — and the output must be byte-identical.
    await runEmit(baseOptions());
    const second = snapshot();
    expect(second).toEqual(first);
    // Spot-guard the determinism rule directly: nothing in the bundle carries a timestamp.
    expect(JSON.stringify(first)).not.toMatch(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/);
  });
});

// Small helper: readdirSync with dirents (kept local to the determinism test).
import { readdirSync } from "node:fs";
function readFileSyncDirents(dir: string) {
  return readdirSync(dir, { withFileTypes: true });
}

describe("readPriorBundleMetadata / resolvePreviousBuildId units", () => {
  let dir: string;
  beforeEach(() => {
    dir = mkdtempSync(path.join(os.tmpdir(), "adapter-k8s-emit-meta-"));
  });
  afterEach(() => rmSync(dir, { recursive: true, force: true }));

  it("returns null ONLY for a genuinely absent file", () => {
    expect(readPriorBundleMetadata(dir, { releaseName: RELEASE, namespace: "default" })).toBeNull();
  });

  it("rejects a prior buildId that fails assertSafeBuildId (values-yaml injection sink)", () => {
    writeFileSync(
      path.join(dir, "emit-metadata.json"),
      JSON.stringify({ emitVersion: 1, buildId: 'bad"id\n' }),
    );
    expect(() =>
      readPriorBundleMetadata(dir, { releaseName: RELEASE, namespace: "default" }),
    ).toThrow();
  });

  it("rejects a missing buildId as invalid, never as first-deploy", () => {
    writeFileSync(path.join(dir, "emit-metadata.json"), JSON.stringify({ emitVersion: 1 }));
    expect(() =>
      readPriorBundleMetadata(dir, { releaseName: RELEASE, namespace: "default" }),
    ).toThrow(/NOT a first deploy/);
  });

  it("resolvePreviousBuildId: explicit flag wins over the prior bundle", () => {
    const prior = {
      emitVersion: 1,
      buildId: "bundlebuild",
      previousBuildId: null,
      releaseName: RELEASE,
      namespace: "default",
      registry: REGISTRY,
      digests: {},
      cdnTag: "t",
      poolTopology: ["ssr"],
      defaultPool: "ssr",
      targetPlatforms: {},
      secretsMode: "external" as const,
    };
    expect(
      resolvePreviousBuildId({
        buildId: BUILD,
        previousBuildFlag: "flagbuild",
        firstDeploy: false,
        priorBundle: prior,
        bundleDir: dir,
      }).previousBuildId,
    ).toBe("flagbuild");
  });

  it("resolvePreviousBuildId: prior bundle supplies previous build, default pool and topology", () => {
    const prior = {
      emitVersion: 1,
      buildId: PREV_BUILD,
      previousBuildId: null,
      releaseName: RELEASE,
      namespace: "default",
      registry: REGISTRY,
      digests: {},
      cdnTag: "t",
      poolTopology: ["ssr", "api"],
      defaultPool: "api",
      targetPlatforms: {},
      secretsMode: "external" as const,
    };
    expect(
      resolvePreviousBuildId({
        buildId: BUILD,
        previousBuildFlag: undefined,
        firstDeploy: false,
        priorBundle: prior,
        bundleDir: dir,
      }),
    ).toEqual({
      previousBuildId: PREV_BUILD,
      previousDefaultPool: "api",
      previousPools: ["ssr", "api"],
    });
  });
});

describe("renderBundleReadme", () => {
  const meta: EmitMetadata = {
    emitVersion: 1,
    buildId: BUILD,
    previousBuildId: PREV_BUILD,
    releaseName: RELEASE,
    namespace: "default",
    registry: REGISTRY,
    digests: { ssr: DIGEST_SSR },
    cdnTag: `build-${"0".repeat(64)}`,
    poolTopology: ["ssr"],
    defaultPool: "ssr",
    targetPlatforms: { [BUILD]: "linux/amd64" },
    secretsMode: "external",
  };

  it("states the cutover model and the pinned selector build", () => {
    const readme = renderBundleReadme(meta);
    expect(readme).toContain("cutover.mode: none");
    expect(readme).toContain(PREV_BUILD);
    expect(readme).toContain("docs/ci-cd.md");
  });

  it("warns about inline secrets in inline mode", () => {
    const readme = renderBundleReadme({ ...meta, secretsMode: "inline" });
    expect(readme).toContain("INLINE");
    expect(readme).toContain("REAL credentials");
  });
});
