// tests/cli/emit.test.ts
//
// GitOps PR1 (`adapter-k8s emit`, cutover.mode: none). The review-critical surface is the
// previous-build/first-deploy input semantics — N20's new front door — so those tests come
// first and are exhaustive about the fail-closed distinctions ("no prior bundle" ≠ "first
// deploy"; "corrupt prior bundle" ≠ "no prior bundle"). Bundle assembly runs against a real
// temp directory (real fs, like state.test.ts) with only subprocess seams mocked.
import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import path from "node:path";
import os from "node:os";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";

vi.mock("../../src/cli/exec.js");
vi.mock("../../src/pipeline/digests.js", async (importOriginal) => {
  const actual = await importOriginal<typeof import("../../src/pipeline/digests.js")>();
  return { ...actual, resolveDeployImageDigests: vi.fn() };
});

import { execCapture, execOrThrow } from "../../src/cli/exec.js";
import { resolveDeployImageDigests } from "../../src/pipeline/digests.js";
import {
  EMIT_VERSION,
  findSopsConfig,
  parseChartValues,
  readPreviousBundleMetadata,
  readPriorBundleMetadata,
  renderBundleReadme,
  renderRenovateFence,
  resolvePreviousBuildId,
  runEmit,
  type EmitMetadata,
} from "../../src/cli/emit.js";
import { internalSecretName } from "../../src/emit/templates/internal-secret.js";
import { cutoverJobName } from "../../src/emit/templates/cutover-job.js";

const DIGEST_SSR = `sha256:${"a".repeat(64)}`;
const DIGEST_ROUTING = `sha256:${"b".repeat(64)}`;
const CUTOVER_IMAGE = `ghcr.io/next-community/adapter-k8s-cutover@sha256:${"c".repeat(64)}`;
const REGISTRY = "us-central1-docker.pkg.dev/my-project/nextjs";
const RELEASE = "my-app";
const BUILD = "build2abc";
const PREV_BUILD = "build1xyz";

let projectDir: string;
let savedInternalSecretKey: string | undefined;

/** The stable key file that satisfies the inline/sops would-mint-fresh guard. */
function writeInternalSecretKey(): void {
  mkdirSync(path.join(projectDir, ".k8s-adapter"), { recursive: true });
  writeFileSync(path.join(projectDir, ".k8s-adapter", "internal-secret.key"), "0".repeat(64));
}

function chartValuesFixture(buildId: string, cutoverGate = false): string {
  const values = {
    global: {
      targetArchitecture: "amd64",
      image: { registry: REGISTRY, repository: "nextjs-app", tag: buildId },
      networkPolicy: { podCidrs: [], nodeCidrs: [], strict: true },
    },
    pools: {
      ssr: {
        image: { repository: "nextjs-app-ssr", digest: "" },
        replicas: { min: 1, max: 3, targetCPU: 80 },
      },
    },
    routingService: { image: { digest: "" } },
    gateway: {},
    build: { id: buildId, nextVersion: "16.0.0", containerStrategy: "traced-assets" },
    activeBuildId: buildId,
    activeDefaultPool: "ssr",
    poolHealthCheckPath: "/readyz",
    // GitOps PR2: the chart's own cutover values gate (values-yaml.ts). Opt-in here so the
    // PR1 tests keep exercising a chart WITHOUT it — `--cutover job` must refuse such a
    // chart rather than emit a bundle that looks job-mode and behaves as mode none.
    ...(cutoverGate
      ? {
          cutover: {
            mode: "none",
            image: "ghcr.io/next-community/adapter-k8s-cutover:latest",
            forcePromotion: false,
          },
          previousBuildId: buildId,
          previousDefaultPool: "ssr",
        }
      : {}),
  };
  return (
    `# Auto-generated by @next-community/adapter-k8s (provider: gke)\n` +
    `# Build ID: ${buildId}\n# Next.js: 16.0.0\n` +
    JSON.stringify(values, null, 2)
  );
}

function writeFixture(opts?: {
  buildId?: string;
  nodeCidrs?: string[];
  podCidrs?: string[];
  omitValkey?: boolean;
  imagePullSecrets?: string[];
  /** Render the build's values.yaml with the PR2 `cutover` values gate present. */
  cutoverGate?: boolean;
}): void {
  const buildId = opts?.buildId ?? BUILD;
  const outputDir = path.join(projectDir, ".k8s-adapter", "output");
  const chartDir = path.join(outputDir, "chart", "templates");
  mkdirSync(chartDir, { recursive: true });
  writeFileSync(
    path.join(projectDir, ".k8s-adapter", "infrastructure.json"),
    JSON.stringify({ containerRegistry: REGISTRY, namespace: "default" }),
  );
  writeFileSync(
    path.join(outputDir, "build-metadata.json"),
    JSON.stringify({
      buildId,
      nextVersion: "16.0.0",
      provider: "gke",
      namespace: "default",
      containerRegistry: REGISTRY,
      pools: ["ssr"],
      defaultPool: "ssr",
      distDir: ".next",
      containerStrategy: "traced-assets",
      hasMiddleware: true,
      failureModeAllow: false,
      cacheEnabled: false,
      cacheManaged: false,
      incrementalCacheHandler: false,
      ...(opts?.nodeCidrs ? { nodeCidrs: opts.nodeCidrs } : {}),
      ...(opts?.podCidrs ? { podCidrs: opts.podCidrs } : {}),
      ...(opts?.imagePullSecrets ? { imagePullSecrets: opts.imagePullSecrets } : {}),
    }),
  );
  writeFileSync(
    path.join(outputDir, "chart", "values.yaml"),
    chartValuesFixture(buildId, opts?.cutoverGate === true),
  );
  writeFileSync(path.join(outputDir, "chart", "Chart.yaml"), `apiVersion: v2\nname: ${RELEASE}\n`);
  writeFileSync(
    path.join(chartDir, "internal-secret.yaml"),
    `apiVersion: v1\nkind: Secret\nmetadata:\n  name: ${internalSecretName(RELEASE, buildId)}\nstringData:\n  secret: "hunter2"\n`,
  );
  if (!opts?.omitValkey) {
    writeFileSync(
      path.join(chartDir, "valkey-secret.yaml"),
      `apiVersion: v1\nkind: Secret\nmetadata:\n  name: ${RELEASE}-valkey\nstringData:\n  url: "redis://cache:6379"\n`,
    );
  }
  writeFileSync(
    path.join(chartDir, "ssr-deployment.yaml"),
    "apiVersion: apps/v1\nkind: Deployment\n" +
      // The build bakes config imagePullSecrets into the pod spec (renderDeployment);
      // mirror that here so the bundle-copy assertion below exercises the pass-through.
      (opts?.imagePullSecrets?.length
        ? `spec:\n  template:\n    spec:\n      imagePullSecrets:\n${opts.imagePullSecrets
            .map((s) => `        - name: "${s}"`)
            .join("\n")}\n`
        : ""),
  );
}

function priorBundleFixture(overrides?: Partial<EmitMetadata>): void {
  const bundleDir = path.join(projectDir, ".k8s-adapter", "gitops");
  mkdirSync(bundleDir, { recursive: true });
  writeFileSync(
    path.join(bundleDir, "emit-metadata.json"),
    JSON.stringify({
      emitVersion: EMIT_VERSION,
      buildId: PREV_BUILD,
      previousBuildId: null,
      releaseName: RELEASE,
      namespace: "default",
      registry: REGISTRY,
      digests: {},
      cdnTag: "build-" + "0".repeat(64),
      poolTopology: ["ssr"],
      defaultPool: "ssr",
      targetPlatforms: { [PREV_BUILD]: "linux/amd64" },
      secretsMode: "external",
      ...overrides,
    }),
  );
}

function bundleValues(): Record<string, unknown> {
  return parseChartValues(
    readFileSync(path.join(projectDir, ".k8s-adapter", "gitops", "values", "values.yaml"), "utf-8"),
  ).values;
}

function bundleMetadata(): EmitMetadata {
  return JSON.parse(
    readFileSync(path.join(projectDir, ".k8s-adapter", "gitops", "emit-metadata.json"), "utf-8"),
  );
}

const baseOptions = () => ({
  projectDir,
  releaseName: RELEASE,
  skipBuild: true,
  skipPush: true,
  // Every runEmit test provides CIDRs or opts out explicitly; the dedicated CIDR tests
  // exercise the fail-closed default.
});

const jobOptions = (extra: Record<string, unknown> = {}) => ({
  ...baseOptions(),
  previousBuild: PREV_BUILD,
  cutover: "job" as const,
  cutoverImage: CUTOVER_IMAGE,
  ...extra,
});

beforeEach(() => {
  vi.clearAllMocks();
  projectDir = mkdtempSync(path.join(os.tmpdir(), "adapter-k8s-emit-"));
  // The stable-key guard (inline/sops) reads this env var — isolate it per test.
  savedInternalSecretKey = process.env.ADAPTER_K8S_INTERNAL_SECRET_KEY;
  delete process.env.ADAPTER_K8S_INTERNAL_SECRET_KEY;
  delete process.env.ADAPTER_K8S_CUTOVER_IMAGE;
  vi.mocked(resolveDeployImageDigests).mockResolvedValue({
    ssr: DIGEST_SSR,
    routingService: DIGEST_ROUTING,
  });
  // helm absent by default (probe fails) — the manifests step then records a skip note.
  vi.mocked(execCapture).mockResolvedValue({ exitCode: 1, stdout: "", stderr: "" });
  vi.mocked(execOrThrow).mockResolvedValue(undefined);
});

afterEach(() => {
  rmSync(projectDir, { recursive: true, force: true });
  if (savedInternalSecretKey !== undefined) {
    process.env.ADAPTER_K8S_INTERNAL_SECRET_KEY = savedInternalSecretKey;
  } else {
    delete process.env.ADAPTER_K8S_INTERNAL_SECRET_KEY;
  }
});

describe("previous-build semantics (N20's new front door)", () => {
  it("REFUSES when there is no prior bundle and no explicit flag — never infers first deploy", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await expect(runEmit(baseOptions())).rejects.toThrow(/--first-deploy/);
    await expect(runEmit(baseOptions())).rejects.toThrow(/Refusing to infer a first deploy/);
    // Nothing was written.
    expect(existsSync(path.join(projectDir, ".k8s-adapter", "gitops"))).toBe(false);
  });

  it("--first-deploy renders the selectors at the NEW build", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await runEmit({ ...baseOptions(), firstDeploy: true });
    expect(bundleValues().activeBuildId).toBe(BUILD);
    expect(bundleMetadata().previousBuildId).toBeNull();
  });

  it("--previous-build pins activeBuildId to the SANITIZED previous build (the deploy.ts trick at values-write time)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await runEmit({ ...baseOptions(), previousBuild: "123old" });
    // sanitizeK8sName prefixes ids that start with a digit — byte-identical to the pod label.
    expect(bundleValues().activeBuildId).toBe("b-123old");
    expect(bundleMetadata().previousBuildId).toBe("123old");
  });

  it("reads the previous build from the prior bundle's emit-metadata.json (the normal CI flow)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    priorBundleFixture();
    await runEmit(baseOptions());
    expect(bundleValues().activeBuildId).toBe(PREV_BUILD);
    expect(bundleMetadata().previousBuildId).toBe(PREV_BUILD);
  });

  it("a present-but-corrupt prior bundle THROWS — it is not a first deploy", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    const bundleDir = path.join(projectDir, ".k8s-adapter", "gitops");
    mkdirSync(bundleDir, { recursive: true });
    writeFileSync(path.join(bundleDir, "emit-metadata.json"), "{ truncated");
    await expect(runEmit(baseOptions())).rejects.toThrow(/NOT a first deploy/);
  });

  it("a prior bundle from ANOTHER release is refused, not consumed", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    priorBundleFixture({ releaseName: "other-app" });
    await expect(runEmit(baseOptions())).rejects.toThrow(/emitted for release "other-app"/);
  });

  it("a prior bundle from ANOTHER namespace is refused", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    priorBundleFixture({ namespace: "staging" });
    await expect(runEmit(baseOptions())).rejects.toThrow(/emitted for namespace "staging"/);
  });

  it("a prior bundle with a NEWER emitVersion is refused (unknowable layout)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    priorBundleFixture({ emitVersion: EMIT_VERSION + 1 });
    await expect(runEmit(baseOptions())).rejects.toThrow(/emitVersion/);
  });

  it("--first-deploy with an existing prior bundle contradicts and refuses", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    priorBundleFixture();
    await expect(runEmit({ ...baseOptions(), firstDeploy: true })).rejects.toThrow(
      /prior bundle exists/,
    );
  });

  it("--previous-build and --first-deploy together contradict and refuse", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await expect(
      runEmit({ ...baseOptions(), previousBuild: PREV_BUILD, firstDeploy: true }),
    ).rejects.toThrow(/contradict/);
  });

  it("re-emitting the SAME build reuses the prior bundle's own previousBuildId (idempotent, no N14 trip)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    priorBundleFixture({ buildId: BUILD, previousBuildId: PREV_BUILD });
    await runEmit(baseOptions());
    expect(bundleValues().activeBuildId).toBe(PREV_BUILD);
    expect(bundleMetadata().previousBuildId).toBe(PREV_BUILD);
  });

  it("N14: a previous build IDENTICAL to the new build id is refused (deploymentId signature)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await expect(runEmit({ ...baseOptions(), previousBuild: BUILD })).rejects.toThrow(
      /IDENTICAL to the currently-serving build/,
    );
  });

  it("validates a flag-supplied previous build id at the point of consumption", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await expect(runEmit({ ...baseOptions(), previousBuild: "bad,id\\injection" })).rejects.toThrow(
      /build/i,
    );
  });

  it("runs the CROSS-BUILD collision guard against the prior bundle's recorded topology", async () => {
    // The prior build id differs from the new one (so N14 passes) but sanitizes to the
    // SAME composed Deployment name (lowercasing erases the difference) — the exact class
    // the bare-id comparison cannot see. The prior bundle's poolTopology supplies the
    // previous pools, standing in for the cluster emit never contacts.
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    priorBundleFixture({ buildId: "Build2abc" });
    await expect(runEmit(baseOptions())).rejects.toThrow(
      /collides with the currently-serving build/,
    );
  });

  it("--previous-build without a prior bundle WARNS that the cross-build check is skipped (topology unknowable without a cluster)", async () => {
    const warn = vi.spyOn(console, "warn").mockImplementation(() => {});
    try {
      writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
      await runEmit({ ...baseOptions(), previousBuild: PREV_BUILD });
      expect(warn).toHaveBeenCalledWith(
        expect.stringContaining("cross-build name-collision check is skipped"),
      );
      // The degradation is warn-and-continue, never silent-and-continue — and the
      // self-collision guard still ran (the bundle exists, so nothing refused).
      expect(bundleMetadata().previousBuildId).toBe(PREV_BUILD);
    } finally {
      warn.mockRestore();
    }
  });

  it("pins activeDefaultPool to the PREVIOUS build's default pool alongside the selector pin", async () => {
    // The default pool routes unmatched traffic; leaving it at the NEW build's value while
    // the selectors pin to the previous build would split the pre-cutover route decision
    // across two builds.
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    priorBundleFixture({ defaultPool: "api", poolTopology: ["ssr", "api"] });
    await runEmit(baseOptions());
    expect(bundleValues().activeDefaultPool).toBe("api");
    // Recorded so a re-emit of the same build can reproduce the pin (the previous build's
    // default pool exists nowhere else after the wholesale bundle replace).
    expect(bundleMetadata().previousDefaultPool).toBe("api");
  });

  it("a RE-EMIT keeps activeDefaultPool at the PREVIOUS build's pool after a default-pool rename", async () => {
    // The prior bundle's `defaultPool` describes the bundle's OWN build. On a re-emit of
    // the same build after a pool rename, falling back to it would flip activeDefaultPool
    // to the NEW build's pool while activeBuildId stays at the previous build — an
    // origin-Service selector pair that matches nothing (zero endpoints at sync time),
    // and a broken byte-idempotence guarantee. The recorded previousDefaultPool is what
    // makes the second emit reproduce the first.
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    // Previous build's default pool was "legacy"; this build's is "ssr".
    priorBundleFixture({ defaultPool: "legacy", poolTopology: ["legacy"] });
    await runEmit(baseOptions());
    expect(bundleValues().activeDefaultPool).toBe("legacy");

    // Second emit consumes the FIRST bundle (same buildId) — must reproduce the pin.
    await runEmit(baseOptions());
    expect(bundleValues().activeBuildId).toBe(PREV_BUILD);
    expect(bundleValues().activeDefaultPool).toBe("legacy");
    expect(bundleMetadata().previousDefaultPool).toBe("legacy");
  });

  it("rejects a prior bundle whose previousDefaultPool fails the pool-name charset (selector sink)", () => {
    priorBundleFixture({ previousDefaultPool: "bad pool{{ }}" } as never);
    expect(() =>
      readPriorBundleMetadata(path.join(projectDir, ".k8s-adapter", "gitops"), {
        releaseName: RELEASE,
        namespace: "default",
      }),
    ).toThrow(/pool/i);
  });
});

// --previous-bundle (split app/cluster repos — real-cluster gap #7): the prior bundle
// lives in ANOTHER repo's checkout. The flag is authoritative (same-repo lookup skipped)
// and fail-closed (missing/unreadable path is a hard error, never first-deploy).
describe("--previous-bundle (split app/cluster repos — gap #7)", () => {
  let clusterDir: string;

  beforeEach(() => {
    clusterDir = mkdtempSync(path.join(os.tmpdir(), "adapter-k8s-cluster-repo-"));
  });
  afterEach(() => rmSync(clusterDir, { recursive: true, force: true }));

  /** Write a prior bundle into the FOREIGN (cluster-repo) checkout. */
  function foreignBundleFixture(overrides?: Partial<EmitMetadata>): string {
    const bundleDir = path.join(clusterDir, "apps", RELEASE, ".k8s-adapter", "gitops");
    mkdirSync(bundleDir, { recursive: true });
    writeFileSync(
      path.join(bundleDir, "emit-metadata.json"),
      JSON.stringify({
        emitVersion: EMIT_VERSION,
        buildId: PREV_BUILD,
        previousBuildId: null,
        releaseName: RELEASE,
        namespace: "default",
        registry: REGISTRY,
        digests: {},
        cdnTag: "build-" + "0".repeat(64),
        poolTopology: ["ssr"],
        defaultPool: "ssr",
        targetPlatforms: { [PREV_BUILD]: "linux/amd64" },
        secretsMode: "external",
        ...overrides,
      }),
    );
    return bundleDir;
  }

  it("reads the previous build AND default pool from the foreign bundle (happy path)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    const foreign = foreignBundleFixture({ defaultPool: "api", poolTopology: ["ssr", "api"] });
    await runEmit({ ...baseOptions(), previousBundle: foreign });
    expect(bundleValues().activeBuildId).toBe(PREV_BUILD);
    // The previous build's default pool pins alongside the selector — identical to the
    // same-repo path's consumption.
    expect(bundleValues().activeDefaultPool).toBe("api");
    const meta = bundleMetadata();
    expect(meta.previousBuildId).toBe(PREV_BUILD);
    expect(meta.previousDefaultPool).toBe("api");
  });

  it("accepts a path directly to the foreign bundle's emit-metadata.json", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    const foreign = foreignBundleFixture();
    await runEmit({
      ...baseOptions(),
      previousBundle: path.join(foreign, "emit-metadata.json"),
    });
    expect(bundleValues().activeBuildId).toBe(PREV_BUILD);
    expect(bundleMetadata().previousBuildId).toBe(PREV_BUILD);
  });

  it("SKIPS the same-repo lookup entirely when the flag is set (a corrupt same-repo bundle would otherwise throw)", async () => {
    // Behavioral spy: a present-but-corrupt SAME-repo bundle is a guaranteed throw for
    // the same-repo lookup (readPriorBundleMetadata fail-closed). Success here proves
    // that lookup was never consulted — the flag is the single source of truth.
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    const sameRepoBundle = path.join(projectDir, ".k8s-adapter", "gitops");
    mkdirSync(sameRepoBundle, { recursive: true });
    writeFileSync(path.join(sameRepoBundle, "emit-metadata.json"), "{ truncated");
    const foreign = foreignBundleFixture();
    await runEmit({ ...baseOptions(), previousBundle: foreign });
    expect(bundleMetadata().previousBuildId).toBe(PREV_BUILD);
  });

  it("a MISSING path is a hard error — never a fallback to the same-repo bundle or first-deploy", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    // A perfectly valid same-repo prior bundle exists — falling back to it would succeed,
    // so a refusal proves the flag never falls back.
    priorBundleFixture();
    await expect(
      runEmit({ ...baseOptions(), previousBundle: path.join(clusterDir, "no-such-dir") }),
    ).rejects.toThrow(/names no prior bundle/);
    await expect(
      runEmit({ ...baseOptions(), previousBundle: path.join(clusterDir, "no-such-dir") }),
    ).rejects.toThrow(/NOT a first deploy/);
    // The same-repo bundle was NOT consumed and nothing was replaced: the fixture's
    // metadata is still exactly what priorBundleFixture wrote.
    expect(bundleMetadata().buildId).toBe(PREV_BUILD);
  });

  it("a corrupt foreign emit-metadata.json throws — it is not a first deploy", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    const foreign = foreignBundleFixture();
    writeFileSync(path.join(foreign, "emit-metadata.json"), "{ truncated");
    await expect(runEmit({ ...baseOptions(), previousBundle: foreign })).rejects.toThrow(
      /NOT a first deploy/,
    );
  });

  it("a foreign bundle from ANOTHER release is refused (same battery as same-repo)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    const foreign = foreignBundleFixture({ releaseName: "other-app" });
    await expect(runEmit({ ...baseOptions(), previousBundle: foreign })).rejects.toThrow(
      /emitted for release "other-app"/,
    );
  });

  it("a foreign bundle from ANOTHER namespace is refused", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    const foreign = foreignBundleFixture({ namespace: "staging" });
    await expect(runEmit({ ...baseOptions(), previousBundle: foreign })).rejects.toThrow(
      /emitted for namespace "staging"/,
    );
  });

  it("a foreign bundle with a NEWER emitVersion is refused (unknowable layout)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    const foreign = foreignBundleFixture({ emitVersion: EMIT_VERSION + 1 });
    await expect(runEmit({ ...baseOptions(), previousBundle: foreign })).rejects.toThrow(
      /emitVersion/,
    );
  });

  it("--previous-bundle + --first-deploy contradict and refuse (before any work)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    const foreign = foreignBundleFixture();
    await expect(
      runEmit({ ...baseOptions(), previousBundle: foreign, firstDeploy: true }),
    ).rejects.toThrow(/contradict/);
    expect(existsSync(path.join(projectDir, ".k8s-adapter", "gitops"))).toBe(false);
  });

  it("--previous-bundle + --previous-build contradict and refuse (one source of truth)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    const foreign = foreignBundleFixture();
    await expect(
      runEmit({ ...baseOptions(), previousBundle: foreign, previousBuild: PREV_BUILD }),
    ).rejects.toThrow(/both given|two sources of truth/);
    expect(existsSync(path.join(projectDir, ".k8s-adapter", "gitops"))).toBe(false);
  });

  it("N14 still fires: a foreign bundle whose previous-build pointer equals the new build is refused", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    // A hand-edited/corrupted cluster-repo bundle recording the new build as both its own
    // and its previous build — the re-emit path consumes previousBuildId, and the N14
    // guard must still catch the identical-build result.
    const foreign = foreignBundleFixture({ buildId: BUILD, previousBuildId: BUILD });
    await expect(runEmit({ ...baseOptions(), previousBundle: foreign })).rejects.toThrow(
      /IDENTICAL to the currently-serving build/,
    );
  });

  it("re-emitting the SAME build via the foreign bundle reuses its own previousBuildId and previousDefaultPool", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    const foreign = foreignBundleFixture({
      buildId: BUILD,
      previousBuildId: PREV_BUILD,
      previousDefaultPool: "legacy",
      defaultPool: "ssr",
    });
    await runEmit({ ...baseOptions(), previousBundle: foreign });
    expect(bundleValues().activeBuildId).toBe(PREV_BUILD);
    expect(bundleValues().activeDefaultPool).toBe("legacy");
    expect(bundleMetadata().previousDefaultPool).toBe("legacy");
  });

  it("runs the CROSS-BUILD collision guard against the foreign bundle's recorded topology", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    // Same class as the same-repo test: differs by case, collides after sanitization.
    const foreign = foreignBundleFixture({ buildId: "Build2abc" });
    await expect(runEmit({ ...baseOptions(), previousBundle: foreign })).rejects.toThrow(
      /collides with the currently-serving build/,
    );
  });

  it("the bundle README documents the split-repo CI recipe with --previous-bundle", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    const foreign = foreignBundleFixture();
    await runEmit({ ...baseOptions(), previousBundle: foreign });
    const readme = readFileSync(
      path.join(projectDir, ".k8s-adapter", "gitops", "README.md"),
      "utf-8",
    );
    expect(readme).toContain("## CI recipe (split app/cluster repos)");
    expect(readme).toContain("--previous-bundle");
    expect(readme).toContain(`../cluster-repo/apps/${RELEASE}/.k8s-adapter/gitops`);
    // The fail-closed posture is stated where the CI author reads it.
    expect(readme).toMatch(/never treated as a first deploy|hard error/);
  });

  it("readPreviousBundleMetadata unit: dir path and metadata path resolve identically; missing throws", () => {
    const foreign = foreignBundleFixture();
    const expected = { releaseName: RELEASE, namespace: "default" };
    expect(readPreviousBundleMetadata(foreign, expected).buildId).toBe(PREV_BUILD);
    expect(
      readPreviousBundleMetadata(path.join(foreign, "emit-metadata.json"), expected).buildId,
    ).toBe(PREV_BUILD);
    expect(() => readPreviousBundleMetadata(path.join(clusterDir, "absent"), expected)).toThrow(
      /names no prior bundle/,
    );
  });
});

describe("CIDR config surface (fail-closed, A4 'replaced')", () => {
  it("REFUSES to render strict NetworkPolicies with no configured node CIDRs", async () => {
    writeFixture(); // no nodeCidrs
    await expect(runEmit({ ...baseOptions(), firstDeploy: true })).rejects.toThrow(
      /networkPolicy\.nodeCidrs/,
    );
  });

  it("--allow-no-network-policy renders strict: false instead", async () => {
    writeFixture();
    await runEmit({ ...baseOptions(), firstDeploy: true, allowNoNetworkPolicy: true });
    const global = bundleValues().global as { networkPolicy: Record<string, unknown> };
    expect(global.networkPolicy.strict).toBe(false);
    expect(global.networkPolicy.nodeCidrs).toEqual([]);
  });

  it("pins configured node + pod CIDRs into the bundle values", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16", "10.1.0.0/16"], podCidrs: ["10.8.0.0/14"] });
    await runEmit({ ...baseOptions(), firstDeploy: true });
    const global = bundleValues().global as { networkPolicy: Record<string, unknown> };
    expect(global.networkPolicy.strict).toBe(true);
    expect(global.networkPolicy.nodeCidrs).toEqual(["10.0.0.0/16", "10.1.0.0/16"]);
    expect(global.networkPolicy.podCidrs).toEqual(["10.8.0.0/14"]);
  });

  it("rejects malformed CIDRs from build metadata at the point of consumption", async () => {
    writeFixture({ nodeCidrs: ["not-a-cidr"] });
    await expect(runEmit({ ...baseOptions(), firstDeploy: true })).rejects.toThrow(/invalid CIDR/);
  });
});

describe("imagePullSecrets (private registries — gap #2)", () => {
  it("carries the configured pull-secret names into emit-metadata.json and the bundle README", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"], imagePullSecrets: ["docker-regcred"] });
    await runEmit({ ...baseOptions(), firstDeploy: true });
    expect(bundleMetadata().imagePullSecrets).toEqual(["docker-regcred"]);
    const readme = readFileSync(
      path.join(projectDir, ".k8s-adapter", "gitops", "README.md"),
      "utf-8",
    );
    // The operator prerequisite: the Secret must exist in the target namespace before a
    // sync — the bundle never carries it.
    expect(readme).toContain("Image pull secrets");
    expect(readme).toContain("`docker-regcred`");
    expect(readme).toContain("ImagePullBackOff");
    // The bundle's chart copy carries the baked pod-spec reference through verbatim.
    const dep = readFileSync(
      path.join(projectDir, ".k8s-adapter", "gitops", "chart", "templates", "ssr-deployment.yaml"),
      "utf-8",
    );
    expect(dep).toMatch(/imagePullSecrets:\n\s+- name: "docker-regcred"/);
  });

  it("omits the key and the README section entirely when unconfigured", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await runEmit({ ...baseOptions(), firstDeploy: true });
    expect(bundleMetadata().imagePullSecrets).toBeUndefined();
    const readme = readFileSync(
      path.join(projectDir, ".k8s-adapter", "gitops", "README.md"),
      "utf-8",
    );
    expect(readme).not.toContain("Image pull secrets");
  });

  it("rejects a build-metadata pull-secret name outside the Secret-name charset (README/metadata sink)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"], imagePullSecrets: ["Bad_Name"] });
    await expect(runEmit({ ...baseOptions(), firstDeploy: true })).rejects.toThrow(
      /Invalid Secret name/,
    );
  });
});

describe("secret externalization", () => {
  it("external (default): omits both secret templates and emits the ExternalSecret placeholder", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await runEmit({ ...baseOptions(), firstDeploy: true });
    const templates = path.join(projectDir, ".k8s-adapter", "gitops", "chart", "templates");
    expect(existsSync(path.join(templates, "internal-secret.yaml"))).toBe(false);
    expect(existsSync(path.join(templates, "valkey-secret.yaml"))).toBe(false);
    const external = readFileSync(path.join(templates, "external-secret.yaml"), "utf-8");
    // The names/keys the pods reference, from the same single sources of truth.
    expect(external).toContain(`name: ${internalSecretName(RELEASE, BUILD)}`);
    expect(external).toContain("secretKey: secret");
    expect(external).toContain(`name: ${RELEASE}-valkey`);
    expect(external).toContain("helm.sh/resource-policy: keep");
    expect(external).toContain("argocd.argoproj.io/sync-options: Prune=false");
    expect(external).toContain("kustomize.toolkit.fluxcd.io/prune: disabled");
    // Gated so a bundle without a store renders nothing rather than failing.
    expect(external).toContain("{{- if and .Values.externalSecrets");
    expect(bundleMetadata().secretsMode).toBe("external");
    // The README documents the required Secret names/keys.
    const readme = readFileSync(
      path.join(projectDir, ".k8s-adapter", "gitops", "README.md"),
      "utf-8",
    );
    expect(readme).toContain("Secrets (externalized)");
    expect(readme).toContain(`${RELEASE}-valkey`);
  });

  it("external: NO stringData secret material survives anywhere in the bundle (whole-tree scan)", async () => {
    // Belt-and-braces over the filename-based exclusion above: scan every emitted file.
    // If a THIRD secret-bearing template ever appears (the S25 hazard emit/helm.ts guards
    // against), the copy loop's SECRET_CHART_FILES check would miss it — this catches the
    // credential in the output no matter which file carries it.
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await runEmit({ ...baseOptions(), firstDeploy: true });
    const bundleDir = path.join(projectDir, ".k8s-adapter", "gitops");
    const offenders: string[] = [];
    const walk = (dir: string, prefix: string): void => {
      for (const entry of readFileSyncDirents(dir)) {
        const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
        if (entry.isDirectory()) walk(path.join(dir, entry.name), rel);
        else {
          const body = readFileSync(path.join(dir, entry.name), "utf-8");
          if (/^\s*stringData:/m.test(body) || body.includes("hunter2")) offenders.push(rel);
        }
      }
    };
    walk(bundleDir, "");
    expect(offenders).toEqual([]);
  });

  it("external without a cache: no Valkey ExternalSecret is emitted", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"], omitValkey: true });
    await runEmit({ ...baseOptions(), firstDeploy: true });
    const external = readFileSync(
      path.join(projectDir, ".k8s-adapter", "gitops", "chart", "templates", "external-secret.yaml"),
      "utf-8",
    );
    expect(external).not.toContain(`name: ${RELEASE}-valkey`);
  });

  it("inline keeps the secret templates verbatim and warns loudly", async () => {
    const warn = vi.spyOn(console, "warn").mockImplementation(() => {});
    try {
      writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
      writeInternalSecretKey(); // inline embeds the secret — the stable-key guard applies
      await runEmit({ ...baseOptions(), firstDeploy: true, secrets: "inline" });
      const templates = path.join(projectDir, ".k8s-adapter", "gitops", "chart", "templates");
      expect(readFileSync(path.join(templates, "internal-secret.yaml"), "utf-8")).toContain(
        "hunter2",
      );
      expect(existsSync(path.join(templates, "external-secret.yaml"))).toBe(false);
      expect(warn).toHaveBeenCalledWith(expect.stringContaining("REAL credentials"));
      expect(bundleMetadata().secretsMode).toBe("inline");
    } finally {
      warn.mockRestore();
    }
  });

  it("rejects an unknown secrets mode", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await expect(
      runEmit({ ...baseOptions(), firstDeploy: true, secrets: "sealed" as never }),
    ).rejects.toThrow(/--secrets/);
  });

  it("inline REFUSES when the internal-secret key source is unstable (would-mint-fresh — PR1 note #2)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    // No ADAPTER_K8S_INTERNAL_SECRET_KEY (cleared in beforeEach), no key file.
    await expect(
      runEmit({ ...baseOptions(), firstDeploy: true, secrets: "inline" }),
    ).rejects.toThrow(/ADAPTER_K8S_INTERNAL_SECRET_KEY/);
    expect(existsSync(path.join(projectDir, ".k8s-adapter", "gitops"))).toBe(false);
  });

  it("the ENV key alone satisfies the stable-key guard (fresh CI checkout, no key file)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    process.env.ADAPTER_K8S_INTERNAL_SECRET_KEY = "k".repeat(64);
    const warn = vi.spyOn(console, "warn").mockImplementation(() => {});
    try {
      await runEmit({ ...baseOptions(), firstDeploy: true, secrets: "inline" });
      expect(bundleMetadata().secretsMode).toBe("inline");
    } finally {
      warn.mockRestore();
    }
  });
});

// --secrets sops: the sops CLI is mocked at the exec seam (real sops NOT required).
// A successful mock encryption wraps the plaintext in a recognizable envelope carrying a
// per-call nonce (sops embeds fresh data keys/MACs per run — the mock mirrors that
// non-determinism so the reuse test proves something); decryption unwraps it.
describe("secret externalization: --secrets sops", () => {
  const SOPS_PREFIX = "ENC[";
  // NOT reset per mockSops call: fresh encryptions must differ byte-wise across runs
  // (mirroring sops' fresh data keys/MACs), or the reuse/re-encrypt tests prove nothing.
  let nonce = 0;

  function mockSops(opts?: {
    absent?: boolean;
    encryptExit?: number;
    encryptStderr?: string;
    decryptFails?: boolean;
  }): void {
    vi.mocked(execCapture).mockImplementation(async (cmd, args, execOpts) => {
      if (cmd === "sops") {
        if (opts?.absent) throw Object.assign(new Error("spawn sops ENOENT"), { code: "ENOENT" });
        if (args[0] === "--version") return { exitCode: 0, stdout: "sops 3.9.0", stderr: "" };
        const fileArg = args[args.length - 1]!;
        const filePath = path.resolve((execOpts as { cwd?: string })?.cwd ?? "", fileArg);
        const body = readFileSync(filePath, "utf-8");
        if (args.includes("--encrypt")) {
          if (opts?.encryptExit) {
            return {
              exitCode: opts.encryptExit,
              stdout: "",
              stderr: opts.encryptStderr ?? "config file not found",
            };
          }
          nonce++;
          return {
            exitCode: 0,
            stdout: `${SOPS_PREFIX}${nonce}]\n${body}\nsops:\n  mac: mac-${nonce}\n`,
            stderr: "",
          };
        }
        if (args.includes("--decrypt")) {
          if (opts?.decryptFails) {
            return { exitCode: 128, stdout: "", stderr: "no matching age key" };
          }
          const m = body.match(/^ENC\[\d+\]\n([\s\S]*?)\nsops:\n/);
          if (!m) return { exitCode: 1, stdout: "", stderr: "not an encrypted file" };
          return { exitCode: 0, stdout: m[1]!, stderr: "" };
        }
      }
      // helm probe: absent by default, as in beforeEach.
      return { exitCode: 1, stdout: "", stderr: "" };
    });
  }

  function writeSopsRepoConfig(): void {
    // Repo root = projectDir; the walk up from .k8s-adapter/gitops/ finds it.
    writeFileSync(
      path.join(projectDir, ".sops.yaml"),
      `creation_rules:\n  - path_regex: .*\\.sops\\.yaml$\n    age: age1example\n`,
    );
  }

  const sopsOptions = () => ({ ...baseOptions(), firstDeploy: true, secrets: "sops" as const });

  function secretsDirFiles(): string[] {
    const dir = path.join(projectDir, ".k8s-adapter", "gitops", "secrets");
    return existsSync(dir) ? readdirSync(dir).sort() : [];
  }

  it("encrypts the secret manifests into secrets/*.sops.yaml and excludes the templates from chart/ (like external)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    writeInternalSecretKey();
    writeSopsRepoConfig();
    mockSops();
    await runEmit(sopsOptions());
    expect(secretsDirFiles()).toEqual(["internal-secret.sops.yaml", "valkey-secret.sops.yaml"]);
    const enc = readFileSync(
      path.join(projectDir, ".k8s-adapter", "gitops", "secrets", "internal-secret.sops.yaml"),
      "utf-8",
    );
    // The encrypted envelope carries the plaintext object (mock) plus sops metadata.
    expect(enc).toContain("sops:");
    expect(enc.startsWith(SOPS_PREFIX)).toBe(true);
    // Chart exclusion — the sops files are applied by the GitOps engine, not Helm.
    const templates = path.join(projectDir, ".k8s-adapter", "gitops", "chart", "templates");
    expect(existsSync(path.join(templates, "internal-secret.yaml"))).toBe(false);
    expect(existsSync(path.join(templates, "valkey-secret.yaml"))).toBe(false);
    // No ExternalSecret placeholder either — that is external mode's artifact.
    expect(existsSync(path.join(templates, "external-secret.yaml"))).toBe(false);
    const meta = bundleMetadata();
    expect(meta.secretsMode).toBe("sops");
    expect(meta.sopsFiles).toEqual([
      "secrets/internal-secret.sops.yaml",
      "secrets/valkey-secret.sops.yaml",
    ]);
  });

  it("sops runs with cwd at the .sops.yaml directory and NO recipients on argv", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    writeInternalSecretKey();
    writeSopsRepoConfig();
    mockSops();
    await runEmit(sopsOptions());
    const encryptCalls = vi
      .mocked(execCapture)
      .mock.calls.filter(([cmd, args]) => cmd === "sops" && args.includes("--encrypt"));
    expect(encryptCalls.length).toBe(2);
    for (const [, args, execOpts] of encryptCalls) {
      // The repo's creation_rules govern: cwd is the config's directory, and neither
      // recipients nor --config appear on argv (discovery, like a human running sops).
      expect((execOpts as { cwd?: string }).cwd).toBe(projectDir);
      expect(args.join(" ")).not.toMatch(/--age|--pgp|--kms|--config/);
    }
  });

  it("--sops-config uses the named config explicitly (escape hatch)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    writeInternalSecretKey();
    const configPath = path.join(projectDir, "custom-sops-config.yaml");
    writeFileSync(configPath, "creation_rules: []\n");
    mockSops();
    await runEmit({ ...sopsOptions(), sopsConfig: configPath });
    const encryptCalls = vi
      .mocked(execCapture)
      .mock.calls.filter(([cmd, args]) => cmd === "sops" && args.includes("--encrypt"));
    expect(encryptCalls.length).toBe(2);
    for (const [, args] of encryptCalls) {
      expect(args).toContain("--config");
      expect(args).toContain(configPath);
    }
  });

  it("FAIL-CLOSED: sops binary missing is a hard error naming the flag — never plaintext", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    writeInternalSecretKey();
    writeSopsRepoConfig();
    mockSops({ absent: true });
    await expect(runEmit(sopsOptions())).rejects.toThrow(/--secrets sops requires the `sops`/);
    // Refused before the bundle write — nothing (plaintext or otherwise) was emitted.
    expect(existsSync(path.join(projectDir, ".k8s-adapter", "gitops"))).toBe(false);
  });

  it("FAIL-CLOSED: no .sops.yaml found is a hard error — never a plaintext fallback", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    writeInternalSecretKey();
    mockSops(); // binary present; config absent (none written anywhere up the tree)
    await expect(runEmit(sopsOptions())).rejects.toThrow(/no \.sops\.yaml/);
    expect(existsSync(path.join(projectDir, ".k8s-adapter", "gitops"))).toBe(false);
  });

  it("FAIL-CLOSED: a nonzero sops exit is a hard error carrying its stderr, and the plaintext is removed", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    writeInternalSecretKey();
    writeSopsRepoConfig();
    mockSops({ encryptExit: 3, encryptStderr: "no matching creation rules" });
    await expect(runEmit(sopsOptions())).rejects.toThrow(/no matching creation rules/);
    // The failed file's plaintext must NOT survive in the bundle.
    for (const f of secretsDirFiles()) {
      const body = readFileSync(
        path.join(projectDir, ".k8s-adapter", "gitops", "secrets", f),
        "utf-8",
      );
      expect(body).not.toContain("hunter2");
      expect(body).not.toContain("redis://cache:6379");
    }
  });

  it("FAIL-CLOSED: exit 0 with no sops metadata block is still an error (not an encrypted file)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    writeInternalSecretKey();
    writeSopsRepoConfig();
    let calls = 0;
    vi.mocked(execCapture).mockImplementation(async (cmd, args) => {
      if (cmd === "sops" && args[0] === "--version") {
        return { exitCode: 0, stdout: "sops 3.9.0", stderr: "" };
      }
      if (cmd === "sops" && args.includes("--encrypt")) {
        calls++;
        return {
          exitCode: 0,
          stdout: "kind: Secret\nstringData:\n  secret: hunter2\n",
          stderr: "",
        };
      }
      return { exitCode: 1, stdout: "", stderr: "" };
    });
    await expect(runEmit(sopsOptions())).rejects.toThrow(/no sops metadata block/);
    expect(calls).toBeGreaterThan(0);
  });

  it("REFUSES when the internal-secret key source is unstable (would-mint-fresh — PR1 note #2)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    writeSopsRepoConfig();
    mockSops();
    // No env key (cleared in beforeEach), no .k8s-adapter/internal-secret.key.
    await expect(runEmit(sopsOptions())).rejects.toThrow(/ADAPTER_K8S_INTERNAL_SECRET_KEY/);
    expect(existsSync(path.join(projectDir, ".k8s-adapter", "gitops"))).toBe(false);
  });

  it("RE-EMIT reuses an existing encrypted file that still decrypts to the same plaintext (quiet diff)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    writeInternalSecretKey();
    writeSopsRepoConfig();
    mockSops();
    await runEmit({ ...sopsOptions(), firstDeploy: false, previousBuild: PREV_BUILD });
    const firstBytes = readFileSync(
      path.join(projectDir, ".k8s-adapter", "gitops", "secrets", "internal-secret.sops.yaml"),
      "utf-8",
    );
    // Second emit of the SAME build (consumes the first bundle's metadata). The mock's
    // nonce guarantees a re-encryption would produce DIFFERENT bytes — identical bytes
    // prove the decrypt-and-compare reuse path ran.
    await runEmit({ ...baseOptions(), secrets: "sops" });
    const secondBytes = readFileSync(
      path.join(projectDir, ".k8s-adapter", "gitops", "secrets", "internal-secret.sops.yaml"),
      "utf-8",
    );
    expect(secondBytes).toBe(firstBytes);
    // And a decrypt call happened for the reuse check.
    expect(
      vi
        .mocked(execCapture)
        .mock.calls.some(([cmd, args]) => cmd === "sops" && args.includes("--decrypt")),
    ).toBe(true);
  });

  it("RE-EMIT re-encrypts when the existing file no longer decrypts (recipients rotated)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    writeInternalSecretKey();
    writeSopsRepoConfig();
    mockSops();
    await runEmit({ ...sopsOptions(), firstDeploy: false, previousBuild: PREV_BUILD });
    const firstBytes = readFileSync(
      path.join(projectDir, ".k8s-adapter", "gitops", "secrets", "internal-secret.sops.yaml"),
      "utf-8",
    );
    mockSops({ decryptFails: true });
    await runEmit({ ...baseOptions(), secrets: "sops" });
    const secondBytes = readFileSync(
      path.join(projectDir, ".k8s-adapter", "gitops", "secrets", "internal-secret.sops.yaml"),
      "utf-8",
    );
    expect(secondBytes).not.toBe(firstBytes);
    expect(secondBytes).toContain("sops:");
  });

  it("sops: NO plaintext secret material survives anywhere in the bundle (whole-tree scan, mock-envelope aware)", async () => {
    // The mock's envelope deliberately carries the plaintext (so decrypt can invert it) —
    // this scan therefore only checks OUTSIDE secrets/: chart/, values/, metadata, README.
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    writeInternalSecretKey();
    writeSopsRepoConfig();
    mockSops();
    await runEmit(sopsOptions());
    const bundleDir = path.join(projectDir, ".k8s-adapter", "gitops");
    const offenders: string[] = [];
    const walk = (dir: string, prefix: string): void => {
      for (const entry of readFileSyncDirents(dir)) {
        const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
        if (rel === "secrets" && entry.isDirectory()) continue;
        if (entry.isDirectory()) walk(path.join(dir, entry.name), rel);
        else {
          const body = readFileSync(path.join(dir, entry.name), "utf-8");
          if (/^\s*stringData:/m.test(body) || body.includes("hunter2")) offenders.push(rel);
        }
      }
    };
    walk(bundleDir, "");
    expect(offenders).toEqual([]);
  });

  it("the README documents the Flux decryption block and the secrets/ determinism caveat", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    writeInternalSecretKey();
    writeSopsRepoConfig();
    mockSops();
    await runEmit(sopsOptions());
    const readme = readFileSync(
      path.join(projectDir, ".k8s-adapter", "gitops", "README.md"),
      "utf-8",
    );
    expect(readme).toContain("Secrets (SOPS-encrypted)");
    expect(readme).toContain("kustomize.toolkit.fluxcd.io");
    expect(readme).toContain("provider: sops");
    expect(readme).toContain("secrets/internal-secret.sops.yaml");
    // The determinism caveat: secrets/ is excluded from byte-determinism, and the
    // reuse rule that keeps re-emit diffs meaningful is stated.
    expect(readme).toMatch(/EXCLUDED from the bundle's byte-determinism/);
    expect(readme).toMatch(/fresh data keys and MACs/);
    expect(readme).toMatch(/REUSES an\s+existing encrypted file/);
    // The retention rule follows the secret material wherever it lives.
    expect(readme).toMatch(/OUTLIVE the sync/);
  });

  it("refuses a rendered secret template that carries Helm template syntax (sops files bypass Helm)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    writeInternalSecretKey();
    writeSopsRepoConfig();
    mockSops();
    // Simulate a Valkey URL that contained a literal "{{" — escapeHelmActions wrote a
    // Helm action into the rendered template, which only Helm would undo.
    const valkeyPath = path.join(
      projectDir,
      ".k8s-adapter",
      "output",
      "chart",
      "templates",
      "valkey-secret.yaml",
    );
    writeFileSync(
      valkeyPath,
      `apiVersion: v1\nkind: Secret\nmetadata:\n  name: ${RELEASE}-valkey\nstringData:\n  url: "redis://user:{{ "{{" }}pw@cache:6379"\n`,
    );
    await expect(runEmit(sopsOptions())).rejects.toThrow(/Helm template syntax/);
  });

  it("findSopsConfig walks up and returns the nearest config; null when none exists", () => {
    const nested = path.join(projectDir, "a", "b", "c");
    mkdirSync(nested, { recursive: true });
    expect(findSopsConfig(nested)).toBeNull();
    writeFileSync(path.join(projectDir, ".sops.yaml"), "creation_rules: []\n");
    expect(findSopsConfig(nested)).toBe(path.join(projectDir, ".sops.yaml"));
    // A nearer config wins.
    writeFileSync(path.join(projectDir, "a", ".sops.yaml"), "creation_rules: []\n");
    expect(findSopsConfig(nested)).toBe(path.join(projectDir, "a", ".sops.yaml"));
  });
});

describe("bundle assembly", () => {
  it("pins resolved digests into values (pool + routingService)", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await runEmit({ ...baseOptions(), firstDeploy: true });
    const values = bundleValues();
    const pools = values.pools as Record<string, { image: { digest: string } }>;
    expect(pools.ssr!.image.digest).toBe(DIGEST_SSR);
    expect((values.routingService as { image: { digest: string } }).image.digest).toBe(
      DIGEST_ROUTING,
    );
    expect(bundleMetadata().digests).toEqual({
      routingService: DIGEST_ROUTING,
      ssr: DIGEST_SSR,
    });
  });

  it("records the per-bundle facts in emit-metadata.json", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await runEmit({ ...baseOptions(), firstDeploy: true });
    const meta = bundleMetadata();
    expect(meta.emitVersion).toBe(EMIT_VERSION);
    expect(meta.buildId).toBe(BUILD);
    expect(meta.releaseName).toBe(RELEASE);
    expect(meta.namespace).toBe("default");
    expect(meta.registry).toBe(REGISTRY);
    expect(meta.poolTopology).toEqual(["ssr"]);
    expect(meta.defaultPool).toBe("ssr");
    expect(meta.cdnTag).toMatch(/^build-[0-9a-f]{64}$/);
    expect(meta.targetPlatforms).toEqual({ [BUILD]: "linux/amd64" });
  });

  it("skips manifests/all.yaml with a recorded note when helm is unavailable", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await runEmit({ ...baseOptions(), firstDeploy: true });
    expect(
      existsSync(path.join(projectDir, ".k8s-adapter", "gitops", "manifests", "all.yaml")),
    ).toBe(false);
    expect(bundleMetadata().manifests).toMatchObject({ skipped: true });
  });

  it("renders manifests/all.yaml via LOCAL `helm template` when helm is present", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    vi.mocked(execCapture).mockImplementation(async (cmd, args) => {
      if (cmd === "helm" && args[0] === "version") {
        return { exitCode: 0, stdout: "v3.15.0", stderr: "" };
      }
      if (cmd === "helm" && args[0] === "template") {
        return { exitCode: 0, stdout: "kind: Deployment\n", stderr: "" };
      }
      throw new Error(`unexpected exec: ${cmd} ${args.join(" ")}`);
    });
    await runEmit({ ...baseOptions(), firstDeploy: true });
    const all = readFileSync(
      path.join(projectDir, ".k8s-adapter", "gitops", "manifests", "all.yaml"),
      "utf-8",
    );
    expect(all).toBe("kind: Deployment\n");
    expect(bundleMetadata().manifests).toBeUndefined();
    // The template call rendered the BUNDLE chart with the BUNDLE values.
    const templateCall = vi
      .mocked(execCapture)
      .mock.calls.find(([cmd, args]) => cmd === "helm" && args[0] === "template")!;
    expect(templateCall[1]).toContain(path.join(projectDir, ".k8s-adapter", "gitops", "chart"));
    expect(templateCall[1]).toContain(
      path.join(projectDir, ".k8s-adapter", "gitops", "values", "values.yaml"),
    );
  });

  it("a FAILING helm template is a hard error, not a skip — a bundle that cannot render must not be committed", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    vi.mocked(execCapture).mockImplementation(async (cmd, args) => {
      if (cmd === "helm" && args[0] === "version") {
        return { exitCode: 0, stdout: "v3.15.0", stderr: "" };
      }
      return { exitCode: 1, stdout: "", stderr: "Error: template: fail" };
    });
    await expect(runEmit({ ...baseOptions(), firstDeploy: true })).rejects.toThrow(
      /helm template failed/,
    );
  });

  it("NEVER touches a cluster: no kubectl, no gcloud get-credentials, no helm upgrade", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await runEmit({ ...baseOptions(), firstDeploy: true });
    for (const call of [
      ...vi.mocked(execCapture).mock.calls,
      ...vi.mocked(execOrThrow).mock.calls,
    ]) {
      const [cmd, args] = call;
      expect(cmd).not.toBe("kubectl");
      expect(`${cmd} ${(args as string[]).join(" ")}`).not.toMatch(/get-credentials|helm upgrade/);
    }
  });

  it("is byte-deterministic: two emits of the same inputs produce identical bundles", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    const bundleDir = path.join(projectDir, ".k8s-adapter", "gitops");
    const snapshot = (): Record<string, string> => {
      const out: Record<string, string> = {};
      const walk = (dir: string, prefix: string): void => {
        for (const entry of readFileSyncDirents(dir)) {
          const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
          if (entry.isDirectory()) walk(path.join(dir, entry.name), rel);
          else out[rel] = readFileSync(path.join(dir, entry.name), "utf-8");
        }
      };
      walk(bundleDir, "");
      return out;
    };

    await runEmit({ ...baseOptions(), previousBuild: PREV_BUILD });
    const first = snapshot();
    // Second run consumes the FIRST bundle's emit-metadata.json (same build → reuses its
    // previousBuildId), so no flag is needed — and the output must be byte-identical.
    await runEmit(baseOptions());
    const second = snapshot();
    expect(second).toEqual(first);
    // Spot-guard the determinism rule directly: nothing in the bundle carries a timestamp.
    expect(JSON.stringify(first)).not.toMatch(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/);
  });
});

describe("update-bot fence (Renovate / Flux image-automation — gap #6)", () => {
  it("emits renovate.json5 at the bundle root with an ignorePaths entry covering the bundle path", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await runEmit({ ...baseOptions(), firstDeploy: true });
    const fence = readFileSync(
      path.join(projectDir, ".k8s-adapter", "gitops", "renovate.json5"),
      "utf-8",
    );
    // The load-bearing entry: the glob must cover the whole bundle directory, so no
    // tag/digest field inside it is ever bot-writable.
    expect(fence).toContain('".k8s-adapter/gitops/**"');
    // The WHY: manifest-digest coupling — a bot edit desyncs the routing pod's
    // fail-closed byte-match check and crashloops it.
    expect(fence).toMatch(/manifest-digest/);
    expect(fence).toMatch(/crashloop/);
    // The HOW: the artifact is a copy source for the repo's EXISTING config, not a file
    // Renovate auto-discovers at this path.
    expect(fence).toMatch(/copy source/i);
    expect(fence).toMatch(/existing renovate config/i);
    // And it parses as JSON5-shaped config (strip comments, tolerate trailing commas).
    const body = fence
      .split("\n")
      .filter((l) => !l.trimStart().startsWith("//"))
      .join("\n")
      .replace(/,(\s*[\]}])/g, "$1")
      .replace(/ignorePaths/, '"ignorePaths"');
    expect(JSON.parse(body)).toEqual({ ignorePaths: [".k8s-adapter/gitops/**"] });
  });

  it("the README's 'Update bots' section directs bots at the app repo and shows the exact merge entry", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await runEmit({ ...baseOptions(), firstDeploy: true });
    const readme = readFileSync(
      path.join(projectDir, ".k8s-adapter", "gitops", "README.md"),
      "utf-8",
    );
    expect(readme).toContain("## Update bots");
    // Point automation at the app repo, never at bundle contents; the bundle updates
    // only by re-emitting.
    expect(readme).toMatch(/APP repo/);
    expect(readme).toMatch(/never at bundle contents/);
    expect(readme).toMatch(/re-emitting/);
    // Flux image-automation is named alongside Renovate — $imagepolicy markers are the
    // same hazard through a different bot.
    expect(readme).toContain("$imagepolicy");
    // The exact additive ignorePaths entry to merge into an EXISTING repo config.
    expect(readme).toContain('"ignorePaths": [".k8s-adapter/gitops/**"]');
    // And the replaces-defaults footgun is called out (ignorePaths is not additive in
    // Renovate itself — the operator must keep their existing entries).
    expect(readme).toMatch(/replaces the defaults/i);
  });

  it("renderRenovateFence is deterministic and scopes the glob to the given bundle path (variant dirs)", () => {
    expect(renderRenovateFence(".k8s-adapter/gitops")).toBe(
      renderRenovateFence(".k8s-adapter/gitops"),
    );
    const variant = renderRenovateFence(".k8s-adapter/gitops.staging");
    expect(variant).toContain('".k8s-adapter/gitops.staging/**"');
    expect(variant).not.toContain('".k8s-adapter/gitops/**"');
    // No timestamps — same N68 rule as the rest of the bundle.
    expect(variant).not.toMatch(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/);
  });
});

// Small helper: readdirSync with dirents (kept local to the determinism test).
import { readdirSync } from "node:fs";
function readFileSyncDirents(dir: string) {
  return readdirSync(dir, { withFileTypes: true });
}

describe("readPriorBundleMetadata / resolvePreviousBuildId units", () => {
  let dir: string;
  beforeEach(() => {
    dir = mkdtempSync(path.join(os.tmpdir(), "adapter-k8s-emit-meta-"));
  });
  afterEach(() => rmSync(dir, { recursive: true, force: true }));

  it("returns null ONLY for a genuinely absent file", () => {
    expect(readPriorBundleMetadata(dir, { releaseName: RELEASE, namespace: "default" })).toBeNull();
  });

  it("rejects a prior buildId that fails assertSafeBuildId (values-yaml injection sink)", () => {
    writeFileSync(
      path.join(dir, "emit-metadata.json"),
      JSON.stringify({ emitVersion: 1, buildId: 'bad"id\n' }),
    );
    expect(() =>
      readPriorBundleMetadata(dir, { releaseName: RELEASE, namespace: "default" }),
    ).toThrow();
  });

  it("rejects a missing buildId as invalid, never as first-deploy", () => {
    writeFileSync(path.join(dir, "emit-metadata.json"), JSON.stringify({ emitVersion: 1 }));
    expect(() =>
      readPriorBundleMetadata(dir, { releaseName: RELEASE, namespace: "default" }),
    ).toThrow(/NOT a first deploy/);
  });

  it("resolvePreviousBuildId: explicit flag wins over the prior bundle", () => {
    const prior = {
      emitVersion: 1,
      buildId: "bundlebuild",
      previousBuildId: null,
      releaseName: RELEASE,
      namespace: "default",
      registry: REGISTRY,
      digests: {},
      cdnTag: "t",
      poolTopology: ["ssr"],
      defaultPool: "ssr",
      targetPlatforms: {},
      secretsMode: "external" as const,
    };
    expect(
      resolvePreviousBuildId({
        buildId: BUILD,
        previousBuildFlag: "flagbuild",
        firstDeploy: false,
        priorBundle: prior,
        bundleDir: dir,
      }).previousBuildId,
    ).toBe("flagbuild");
  });

  it("resolvePreviousBuildId: prior bundle supplies previous build, default pool and topology", () => {
    const prior = {
      emitVersion: 1,
      buildId: PREV_BUILD,
      previousBuildId: null,
      releaseName: RELEASE,
      namespace: "default",
      registry: REGISTRY,
      digests: {},
      cdnTag: "t",
      poolTopology: ["ssr", "api"],
      defaultPool: "api",
      targetPlatforms: {},
      secretsMode: "external" as const,
    };
    expect(
      resolvePreviousBuildId({
        buildId: BUILD,
        previousBuildFlag: undefined,
        firstDeploy: false,
        priorBundle: prior,
        bundleDir: dir,
      }),
    ).toEqual({
      previousBuildId: PREV_BUILD,
      previousDefaultPool: "api",
      previousPools: ["ssr", "api"],
    });
  });
});

describe("renderBundleReadme", () => {
  const meta: EmitMetadata = {
    emitVersion: 1,
    buildId: BUILD,
    previousBuildId: PREV_BUILD,
    releaseName: RELEASE,
    namespace: "default",
    registry: REGISTRY,
    digests: { ssr: DIGEST_SSR },
    cdnTag: `build-${"0".repeat(64)}`,
    poolTopology: ["ssr"],
    defaultPool: "ssr",
    targetPlatforms: { [BUILD]: "linux/amd64" },
    secretsMode: "external",
  };

  it("states the cutover model and the pinned selector build", () => {
    const readme = renderBundleReadme(meta);
    expect(readme).toContain("cutover.mode: none");
    expect(readme).toContain(PREV_BUILD);
    expect(readme).toContain("docs/ci-cd.md");
  });

  it("warns about inline secrets in inline mode", () => {
    const readme = renderBundleReadme({ ...meta, secretsMode: "inline" });
    expect(readme).toContain("INLINE");
    expect(readme).toContain("REAL credentials");
  });

  it("lists configured imagePullSecrets as an operator prerequisite, naming the namespace", () => {
    const readme = renderBundleReadme({
      ...meta,
      imagePullSecrets: ["docker-regcred", "gh-regcred"],
    });
    expect(readme).toContain("Image pull secrets");
    expect(readme).toContain("`docker-regcred`, `gh-regcred`");
    expect(readme).toContain("namespace\n`default`");
    // Unconfigured bundles carry no section (and no scary prerequisite that isn't one).
    expect(renderBundleReadme(meta)).not.toContain("Image pull secrets");
  });

  it("describes the JOB cutover model for a job-mode bundle — never mode none's manual steps", () => {
    // A job-mode bundle whose README hands the operator mode-none's out-of-band cutover
    // instructions sends them to patch selectors the in-cluster Job owns.
    const readme = renderBundleReadme({ ...meta, cutover: "job" });
    expect(readme).toContain("cutover.mode: job");
    expect(readme).toContain("## Cutover model (mode: job)");
    expect(readme).toContain("templates/cutover-job.yaml");
    // The two operator prerequisites, where the bundle-PR reviewer reads them.
    expect(readme).toContain("docker/cutover-job.Dockerfile");
    expect(readme).toContain("BY DIGEST");
    expect(readme).toContain("adapter-k8s migrate");
    expect(readme).not.toContain("mode: none");
    // Absent and explicit none render the identical README (the byte-identical story).
    expect(renderBundleReadme({ ...meta, cutover: "none" })).toBe(renderBundleReadme(meta));
  });
});

// ---------------------------------------------------------------------------
// GitOps PR2 (design §4.2): `emit --cutover job`. Mode NONE must stay byte-identical to
// PR1 output — the flag's whole safety story is "opt in, or nothing changes".
// ---------------------------------------------------------------------------
describe("emit --cutover job (the in-cluster cutover Job's bundle)", () => {
  const chartTemplate = (name: string): string =>
    readFileSync(
      path.join(projectDir, ".k8s-adapter", "gitops", "chart", "templates", name),
      "utf-8",
    );
  const jobTemplates = ["cutover-job.yaml", "cutover-rbac.yaml", "emit-metadata-configmap.yaml"];

  it("renders the Job, its RBAC, and the emit-metadata ConfigMap INTO THE BUNDLE CHART", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"], cutoverGate: true });
    await runEmit(jobOptions());

    // In chart/templates/, not a cutover/ sidecar: an Argo Application sourcing chart/
    // never applies files outside its source path, so a Job that lived only beside the
    // chart would silently never run.
    for (const name of jobTemplates) {
      expect(chartTemplate(name).startsWith('{{- if eq .Values.cutover.mode "job" }}')).toBe(true);
    }
    expect(chartTemplate("cutover-job.yaml")).toContain(`name: ${cutoverJobName(RELEASE, BUILD)}`);
    expect(chartTemplate("cutover-rbac.yaml")).toContain("kind: Role");
    expect(chartTemplate("cutover-rbac.yaml")).not.toContain("ClusterRole");
    // The mounted metadata carries the Job-only facts the gates need but cannot learn from
    // a chart directory the pod does not have.
    const mounted = JSON.parse(
      chartTemplate("emit-metadata-configmap.yaml")
        .split("emit-metadata.json: |-\n")[1]!
        .split("\n{{- end }}")[0]!
        .replace(/^ {4}/gm, ""),
    );
    expect(mounted).toMatchObject({
      buildId: BUILD,
      previousBuildId: PREV_BUILD,
      releaseName: RELEASE,
      namespace: "default",
      registry: REGISTRY,
      cutover: "job",
      hasPortableOrigin: false,
      hasRouteExtJob: false,
      hasEnvoyExtensionPolicy: false,
      cdnEnabled: false,
      targetPlatforms: { [BUILD]: "linux/amd64" },
    });
  });

  it("pins values: cutover.mode job, activeBuildId at the NEW build, selectors at the previous", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"], cutoverGate: true });
    await runEmit(jobOptions());

    const values = bundleValues();
    expect(values.cutover).toMatchObject({ mode: "job", image: CUTOVER_IMAGE });
    // Under mode job activeBuildId is METADATA (no selector renders from it); the stable
    // Services render from previousBuildId, so the sync never repoints traffic.
    expect(values.activeBuildId).toBe(BUILD);
    expect(values.previousBuildId).toBe(PREV_BUILD);
    expect(values.previousDefaultPool).toBe("ssr");
  });

  it("sanitizes the rendered selector value exactly as activeBuildId is (invariant 3)", async () => {
    // An unsanitized selector value matches no pods and drains the Service to zero
    // endpoints — the same clause, on the new render path.
    writeFixture({ buildId: "9build", nodeCidrs: ["10.0.0.0/16"], cutoverGate: true });
    await runEmit(jobOptions({ previousBuild: "9prev" }));
    expect(bundleValues().previousBuildId).toBe("b-9prev");
    expect(bundleValues().activeBuildId).toBe("b-9build");
  });

  it("records the cutover model and the previous default pool in emit-metadata.json", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"], cutoverGate: true });
    await runEmit(jobOptions());
    expect(bundleMetadata()).toMatchObject({
      cutover: "job",
      previousBuildId: PREV_BUILD,
      previousDefaultPool: "ssr",
      hasRouteExtJob: false,
      hasEnvoyExtensionPolicy: false,
      cdnEnabled: false,
      hasPortableOrigin: false,
    });
  });

  it("reflects the BUILD chart's real template set in the Job's gate facts", async () => {
    // The three booleans replace deploy's `existsSync(chart/templates/…)` probes, and they
    // decide whether the D3/D4-D5/E4 steps run at all — so they must come from the build's
    // chart, not from a guess.
    writeFixture({ nodeCidrs: ["10.0.0.0/16"], cutoverGate: true });
    const chartDir = path.join(projectDir, ".k8s-adapter", "output", "chart", "templates");
    for (const f of [
      "route-ext-update-job.yaml",
      "envoy-extension-policy.yaml",
      "cdn-http-filter.yaml",
      "origin-service.yaml",
    ]) {
      writeFileSync(path.join(chartDir, f), "apiVersion: v1\nkind: ConfigMap\n");
    }
    await runEmit(jobOptions());
    expect(bundleMetadata()).toMatchObject({
      hasRouteExtJob: true,
      hasEnvoyExtensionPolicy: true,
      cdnEnabled: true,
      hasPortableOrigin: true,
    });
  });

  it("passes configured imagePullSecrets through to the Job pod (gap #2)", async () => {
    writeFixture({
      nodeCidrs: ["10.0.0.0/16"],
      cutoverGate: true,
      imagePullSecrets: ["regcred"],
    });
    await runEmit(jobOptions());
    expect(chartTemplate("cutover-job.yaml")).toContain('- name: "regcred"');
  });

  it("REFUSES --cutover job without a digest-pinned cutover image", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"], cutoverGate: true });
    await expect(
      runEmit({ ...baseOptions(), previousBuild: PREV_BUILD, cutover: "job" }),
    ).rejects.toThrow(/digest-pinned cutover image/);
    await expect(
      runEmit({
        ...baseOptions(),
        previousBuild: PREV_BUILD,
        cutover: "job",
        cutoverImage: "ghcr.io/next-community/adapter-k8s-cutover:latest",
      }),
    ).rejects.toThrow(/digest-pinned cutover image/);
  });

  it("REFUSES a chart that predates the cutover values gate", async () => {
    // Pinning values alone would produce a bundle that LOOKS job-mode while behaving as
    // mode none — selectors from activeBuildId, no Job, no keep-at-birth.
    writeFixture({ nodeCidrs: ["10.0.0.0/16"] });
    await expect(
      runEmit({ ...baseOptions(), previousBuild: PREV_BUILD, cutover: "job" }),
    ).rejects.toThrow(/requires a chart with the cutover values gate/);
  });

  it("REFUSES an invalid --cutover value before touching the bundle", async () => {
    writeFixture({ nodeCidrs: ["10.0.0.0/16"], cutoverGate: true });
    await expect(
      runEmit({
        ...baseOptions(),
        previousBuild: PREV_BUILD,
        cutover: "hook" as unknown as "job",
      }),
    ).rejects.toThrow(/Invalid --cutover mode "hook": expected "none".*or "job"/s);
    expect(existsSync(path.join(projectDir, ".k8s-adapter", "gitops"))).toBe(false);
  });

  it("--cutover none (and the absent flag) produce a BYTE-IDENTICAL PR1 bundle", async () => {
    // The determinism model, applied to the flag: opting out must change nothing at all —
    // no Job templates, no cutover keys in emit-metadata, no values delta.
    writeFixture({ nodeCidrs: ["10.0.0.0/16"], cutoverGate: true });
    const bundleDir = path.join(projectDir, ".k8s-adapter", "gitops");
    const snapshot = (): Record<string, string> => {
      const out: Record<string, string> = {};
      const walk = (dir: string, prefix: string): void => {
        for (const entry of readFileSyncDirents(dir)) {
          const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
          if (entry.isDirectory()) walk(path.join(dir, entry.name), rel);
          else out[rel] = readFileSync(path.join(dir, entry.name), "utf-8");
        }
      };
      walk(bundleDir, "");
      return out;
    };

    await runEmit({ ...baseOptions(), previousBuild: PREV_BUILD });
    const implicit = snapshot();
    rmSync(bundleDir, { recursive: true, force: true });
    await runEmit({ ...baseOptions(), previousBuild: PREV_BUILD, cutover: "none" });
    const explicit = snapshot();

    expect(explicit).toEqual(implicit);
    for (const name of jobTemplates) {
      expect(Object.keys(implicit)).not.toContain(`chart/templates/${name}`);
    }
    // Mode none keeps the deploy.ts:1193 trick: activeBuildId pinned at the PREVIOUS build,
    // and no cutover fields in the metadata at all.
    expect(bundleValues().activeBuildId).toBe(PREV_BUILD);
    expect(bundleValues().cutover).toMatchObject({ mode: "none" });
    expect(bundleMetadata().cutover).toBeUndefined();
    expect(bundleMetadata().hasRouteExtJob).toBeUndefined();

    // ...and job mode IS a real delta on the same inputs (so the comparison above is not
    // vacuous), while itself staying deterministic across two runs.
    rmSync(bundleDir, { recursive: true, force: true });
    await runEmit(jobOptions());
    const job = snapshot();
    expect(job).not.toEqual(implicit);
    rmSync(bundleDir, { recursive: true, force: true });
    await runEmit(jobOptions());
    expect(snapshot()).toEqual(job);
  });
});
