// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file envoy/extensions/filters/http/ext_proc/v3/processing_mode.proto (package envoy.extensions.filters.http.ext_proc.v3, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_udpa_annotations_status } from "../../../../../../udpa/annotations/status_pb.js";
import { file_validate_validate } from "../../../../../../validate/validate_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file envoy/extensions/filters/http/ext_proc/v3/processing_mode.proto.
 */
export const file_envoy_extensions_filters_http_ext_proc_v3_processing_mode: GenFile = /*@__PURE__*/
  fileDesc("Cj9lbnZveS9leHRlbnNpb25zL2ZpbHRlcnMvaHR0cC9leHRfcHJvYy92My9wcm9jZXNzaW5nX21vZGUucHJvdG8SKWVudm95LmV4dGVuc2lvbnMuZmlsdGVycy5odHRwLmV4dF9wcm9jLnYzItYGCg5Qcm9jZXNzaW5nTW9kZRJvChNyZXF1ZXN0X2hlYWRlcl9tb2RlGAEgASgOMkguZW52b3kuZXh0ZW5zaW9ucy5maWx0ZXJzLmh0dHAuZXh0X3Byb2MudjMuUHJvY2Vzc2luZ01vZGUuSGVhZGVyU2VuZE1vZGVCCPpCBYIBAhABEnAKFHJlc3BvbnNlX2hlYWRlcl9tb2RlGAIgASgOMkguZW52b3kuZXh0ZW5zaW9ucy5maWx0ZXJzLmh0dHAuZXh0X3Byb2MudjMuUHJvY2Vzc2luZ01vZGUuSGVhZGVyU2VuZE1vZGVCCPpCBYIBAhABEmsKEXJlcXVlc3RfYm9keV9tb2RlGAMgASgOMkYuZW52b3kuZXh0ZW5zaW9ucy5maWx0ZXJzLmh0dHAuZXh0X3Byb2MudjMuUHJvY2Vzc2luZ01vZGUuQm9keVNlbmRNb2RlQgj6QgWCAQIQARJsChJyZXNwb25zZV9ib2R5X21vZGUYBCABKA4yRi5lbnZveS5leHRlbnNpb25zLmZpbHRlcnMuaHR0cC5leHRfcHJvYy52My5Qcm9jZXNzaW5nTW9kZS5Cb2R5U2VuZE1vZGVCCPpCBYIBAhABEnAKFHJlcXVlc3RfdHJhaWxlcl9tb2RlGAUgASgOMkguZW52b3kuZXh0ZW5zaW9ucy5maWx0ZXJzLmh0dHAuZXh0X3Byb2MudjMuUHJvY2Vzc2luZ01vZGUuSGVhZGVyU2VuZE1vZGVCCPpCBYIBAhABEnEKFXJlc3BvbnNlX3RyYWlsZXJfbW9kZRgGIAEoDjJILmVudm95LmV4dGVuc2lvbnMuZmlsdGVycy5odHRwLmV4dF9wcm9jLnYzLlByb2Nlc3NpbmdNb2RlLkhlYWRlclNlbmRNb2RlQgj6QgWCAQIQASIxCg5IZWFkZXJTZW5kTW9kZRILCgdERUZBVUxUEAASCAoEU0VORBABEggKBFNLSVAQAiJuCgxCb2R5U2VuZE1vZGUSCAoETk9ORRAAEgwKCFNUUkVBTUVEEAESDAoIQlVGRkVSRUQQAhIUChBCVUZGRVJFRF9QQVJUSUFMEAMSGAoURlVMTF9EVVBMRVhfU1RSRUFNRUQQBBIICgRHUlBDEAVCtQEKN2lvLmVudm95cHJveHkuZW52b3kuZXh0ZW5zaW9ucy5maWx0ZXJzLmh0dHAuZXh0X3Byb2MudjNCE1Byb2Nlc3NpbmdNb2RlUHJvdG9QAVpbZ2l0aHViLmNvbS9lbnZveXByb3h5L2dvLWNvbnRyb2wtcGxhbmUvZW52b3kvZXh0ZW5zaW9ucy9maWx0ZXJzL2h0dHAvZXh0X3Byb2MvdjM7ZXh0X3Byb2N2M7qAyNEGAhACYgZwcm90bzM", [file_udpa_annotations_status, file_validate_validate]);

/**
 * [#next-free-field: 7]
 *
 * @generated from message envoy.extensions.filters.http.ext_proc.v3.ProcessingMode
 */
export type ProcessingMode = Message<"envoy.extensions.filters.http.ext_proc.v3.ProcessingMode"> & {
  /**
   * How to handle the request header.
   *
   * .. note::
   *
   *    This field is ignored in
   *    :ref:`mode_override <envoy_v3_api_field_service.ext_proc.v3.ProcessingResponse.mode_override>`,
   *    since mode overrides can only affect messages exchanged after the request header is
   *    processed.
   *
   * Defaults to ``SEND``.
   *
   * @generated from field: envoy.extensions.filters.http.ext_proc.v3.ProcessingMode.HeaderSendMode request_header_mode = 1;
   */
  requestHeaderMode: ProcessingMode_HeaderSendMode;

  /**
   * How to handle the response header.
   *
   * Defaults to ``SEND``.
   *
   * @generated from field: envoy.extensions.filters.http.ext_proc.v3.ProcessingMode.HeaderSendMode response_header_mode = 2;
   */
  responseHeaderMode: ProcessingMode_HeaderSendMode;

  /**
   * How to handle the request body.
   *
   * Defaults to ``NONE``.
   *
   * @generated from field: envoy.extensions.filters.http.ext_proc.v3.ProcessingMode.BodySendMode request_body_mode = 3;
   */
  requestBodyMode: ProcessingMode_BodySendMode;

  /**
   * How to handle the response body.
   *
   * Defaults to ``NONE``.
   *
   * @generated from field: envoy.extensions.filters.http.ext_proc.v3.ProcessingMode.BodySendMode response_body_mode = 4;
   */
  responseBodyMode: ProcessingMode_BodySendMode;

  /**
   * How to handle the request trailers.
   *
   * Defaults to ``SKIP``.
   *
   * @generated from field: envoy.extensions.filters.http.ext_proc.v3.ProcessingMode.HeaderSendMode request_trailer_mode = 5;
   */
  requestTrailerMode: ProcessingMode_HeaderSendMode;

  /**
   * How to handle the response trailers.
   *
   * Defaults to ``SKIP``.
   *
   * @generated from field: envoy.extensions.filters.http.ext_proc.v3.ProcessingMode.HeaderSendMode response_trailer_mode = 6;
   */
  responseTrailerMode: ProcessingMode_HeaderSendMode;
};

/**
 * Describes the message envoy.extensions.filters.http.ext_proc.v3.ProcessingMode.
 * Use `create(ProcessingModeSchema)` to create a new message.
 */
export const ProcessingModeSchema: GenMessage<ProcessingMode> = /*@__PURE__*/
  messageDesc(file_envoy_extensions_filters_http_ext_proc_v3_processing_mode, 0);

/**
 * Control how headers and trailers are handled.
 *
 * @generated from enum envoy.extensions.filters.http.ext_proc.v3.ProcessingMode.HeaderSendMode
 */
export enum ProcessingMode_HeaderSendMode {
  /**
   * When used to configure the ext_proc filter
   * :ref:`processing_mode <envoy_v3_api_field_extensions.filters.http.ext_proc.v3.ExternalProcessor.processing_mode>`,
   * the default ``HeaderSendMode`` depends on which part of the message is being processed. By
   * default, request and response headers are sent, while trailers are skipped.
   *
   * When used in
   * :ref:`mode_override <envoy_v3_api_field_service.ext_proc.v3.ProcessingResponse.mode_override>`
   * or
   * :ref:`allowed_override_modes <envoy_v3_api_field_extensions.filters.http.ext_proc.v3.ExternalProcessor.allowed_override_modes>`,
   * a value of ``DEFAULT`` indicates that there is no change from the behavior that is configured
   * for the filter in
   * :ref:`processing_mode <envoy_v3_api_field_extensions.filters.http.ext_proc.v3.ExternalProcessor.processing_mode>`.
   *
   * @generated from enum value: DEFAULT = 0;
   */
  DEFAULT = 0,

  /**
   * Send the header or trailer.
   *
   * @generated from enum value: SEND = 1;
   */
  SEND = 1,

  /**
   * Do not send the header or trailer.
   *
   * @generated from enum value: SKIP = 2;
   */
  SKIP = 2,
}

/**
 * Describes the enum envoy.extensions.filters.http.ext_proc.v3.ProcessingMode.HeaderSendMode.
 */
export const ProcessingMode_HeaderSendModeSchema: GenEnum<ProcessingMode_HeaderSendMode> = /*@__PURE__*/
  enumDesc(file_envoy_extensions_filters_http_ext_proc_v3_processing_mode, 0, 0);

/**
 * Control how the request and response bodies are handled.
 *
 * When body mutation by the external processor is enabled, the ext_proc filter will always remove the
 * content length header in the following four cases, unless
 * :ref:`allow_content_length_header <envoy_v3_api_field_extensions.filters.http.ext_proc.v3.ExternalProcessor.allow_content_length_header>`
 * is enabled. This is because the content length cannot be guaranteed to be set correctly:
 *
 * 1) ``STREAMED`` BodySendMode: header processing completes before body mutation comes back.
 * 2) ``BUFFERED_PARTIAL`` BodySendMode: body is buffered and could be injected in different phases.
 * 3) ``BUFFERED`` BodySendMode + ``SKIP`` HeaderSendMode: header processing (e.g., update content-length) is skipped.
 * 4) ``FULL_DUPLEX_STREAMED`` BodySendMode: header processing completes before body mutation comes back.
 *
 * In Envoy's HTTP/1 codec implementation, removing content length will enable chunked transfer
 * encoding whenever feasible. The recipient (either client or server) must be able to parse and
 * decode the chunked transfer coding
 * (see `details in RFC9112 <https://tools.ietf.org/html/rfc9112#section-7.1>`_).
 *
 * In ``BUFFERED`` BodySendMode + ``SEND`` HeaderSendMode, content length header is allowed but it
 * is the external processor's responsibility to set the content length correctly matched to the
 * length of the mutated body. If they don't match, the corresponding body mutation will be
 * rejected and a local reply will be sent with an error message.
 *
 * @generated from enum envoy.extensions.filters.http.ext_proc.v3.ProcessingMode.BodySendMode
 */
export enum ProcessingMode_BodySendMode {
  /**
   * Do not send the body at all. This is the default.
   *
   * @generated from enum value: NONE = 0;
   */
  NONE = 0,

  /**
   * Stream the body to the server in pieces as they are seen.
   *
   * @generated from enum value: STREAMED = 1;
   */
  STREAMED = 1,

  /**
   * Buffer the message body in memory and send the entire body at once.
   * If the body exceeds the configured buffer limit, then the
   * downstream system will receive an error.
   *
   * @generated from enum value: BUFFERED = 2;
   */
  BUFFERED = 2,

  /**
   * Buffer the message body in memory and send the entire body in one
   * chunk. If the body exceeds the configured buffer limit, then the body contents
   * up to the buffer limit will be sent.
   *
   * @generated from enum value: BUFFERED_PARTIAL = 3;
   */
  BUFFERED_PARTIAL = 3,

  /**
   * The ext_proc client (the data plane) streams the body to the server in pieces as they arrive.
   *
   * 1) The server may choose to buffer any number of chunks of data before processing them.
   *    After it finishes buffering, the server processes the buffered data. Then it splits the
   *    processed data into any number of chunks, and streams them back to the ext_proc client one
   *    by one. The server may continuously do so until the complete body is processed. The
   *    individual response chunk size is recommended to be no greater than 64K bytes, or
   *    :ref:`max_receive_message_length <envoy_v3_api_field_config.core.v3.GrpcService.EnvoyGrpc.max_receive_message_length>`
   *    if EnvoyGrpc is used.
   *
   * 2) The server may also choose to buffer the entire message, including the headers (if header
   *    mode is ``SEND``), the entire body, and the trailers (if present), before sending back any
   *    response. The server response has to maintain the headers-body-trailers ordering.
   *
   * 3) Note that the server might also choose not to buffer data. That is, upon receiving a body
   *    request, it could process the data and send back a body response immediately.
   *
   * In this body mode:
   *
   * * The corresponding trailer mode has to be set to ``SEND``.
   * * The client will send body and trailers (if present) to the server as they arrive. Sending
   *   the trailers (if present) is to inform the server that the complete body has arrived. In
   *   case there are no trailers, then the client will set
   *   :ref:`end_of_stream <envoy_v3_api_field_service.ext_proc.v3.HttpBody.end_of_stream>`
   *   to ``true`` as part of the last body chunk request to notify the server that no other data
   *   is to be sent.
   * * The server needs to send
   *   :ref:`StreamedBodyResponse <envoy_v3_api_msg_service.ext_proc.v3.StreamedBodyResponse>`
   *   to the client in the body response.
   * * The client will stream the body chunks in the responses from the server to the
   *   upstream/downstream as they arrive.
   *
   * @generated from enum value: FULL_DUPLEX_STREAMED = 4;
   */
  FULL_DUPLEX_STREAMED = 4,

  /**
   * [#not-implemented-hide:]
   * A mode for gRPC traffic. This is similar to ``FULL_DUPLEX_STREAMED``, except that instead of
   * sending raw chunks of the HTTP/2 DATA frames, the ext_proc client will de-frame the
   * individual gRPC messages inside the HTTP/2 DATA frames, and as each message is de-framed, it
   * will be sent to the ext_proc server as a
   * :ref:`request_body <envoy_v3_api_field_service.ext_proc.v3.ProcessingRequest.request_body>`
   * or
   * :ref:`response_body <envoy_v3_api_field_service.ext_proc.v3.ProcessingRequest.response_body>`.
   * The ext_proc server will stream back individual gRPC messages in the
   * :ref:`StreamedBodyResponse <envoy_v3_api_msg_service.ext_proc.v3.StreamedBodyResponse>`
   * field, but the number of messages sent by the ext_proc server does not need to equal the
   * number of messages sent by the data plane. This allows the ext_proc server to change the
   * number of messages sent on the stream. In this mode, the client will send body and trailers
   * to the server as they arrive.
   *
   * @generated from enum value: GRPC = 5;
   */
  GRPC = 5,
}

/**
 * Describes the enum envoy.extensions.filters.http.ext_proc.v3.ProcessingMode.BodySendMode.
 */
export const ProcessingMode_BodySendModeSchema: GenEnum<ProcessingMode_BodySendMode> = /*@__PURE__*/
  enumDesc(file_envoy_extensions_filters_http_ext_proc_v3_processing_mode, 0, 1);

