// src/emit/templates/values-yaml.ts
import type { K8sAdapterConfig, PoolDefinition } from "../../types.js";
import { sanitizeK8sName } from "./utils.js";

export function renderValuesYaml({
  pools,
  buildId,
  nextVersion,
  config,
  imageRegistry,
}: {
  pools: Map<string, PoolDefinition>;
  buildId: string;
  nextVersion: string;
  config: K8sAdapterConfig;
  imageRegistry: string;
}): string {
  // Output as JSON (valid YAML) with a comment header.
  const gke = "gke" in config.provider ? config.provider.gke : undefined;

  const values = {
    global: {
      image: {
        registry: imageRegistry,
        repository: "nextjs-app",
        tag: buildId,
        pullPolicy: "IfNotPresent",
      },
      // Empty by default: the deploy CLI passes `--set global.networkPolicy.podCidrs=
      // {..}` when it can discover the cluster's pod CIDRs; an empty list renders no
      // NetworkPolicies (the templates are wrapped in a helm `if` guard).
      networkPolicy: {
        podCidrs: [] as string[],
      },
    },
    pools: Object.fromEntries(
      [...pools.entries()].map(([name, pool]) => [
        name,
        {
          image: {
            repository:
              config.containerStrategy === "shared-image" ? "nextjs-app" : `nextjs-app-${name}`,
          },
          replicas: pool.config.scaling ?? { min: 1, max: 3, targetCPU: 80 },
          resources: {
            requests: {
              cpu: pool.config.resources?.cpu ?? "250m",
              memory: pool.config.resources?.memory ?? "256Mi",
            },
            limits: {
              cpu: pool.config.resources?.cpuLimit ?? "1",
              memory: pool.config.resources?.memoryLimit ?? "512Mi",
            },
          },
          _meta: { outputCount: pool.outputs.length },
        },
      ]),
    ),
    gateway: gke?.gateway ?? {},
    build: {
      id: buildId,
      nextVersion,
      containerStrategy: config.containerStrategy ?? "traced-assets",
    },
    activeBuildId: sanitizeK8sName(buildId),
  };

  const header = `# Auto-generated by @next-community/adapter-k8s (provider: gke)\n# Build ID: ${buildId}\n# Next.js: ${nextVersion}\n# Generated: ${new Date().toISOString()}\n`;
  return header + JSON.stringify(values, null, 2);
}
