// src/emit/templates/values-yaml.ts
import type { K8sAdapterConfig, PoolDefinition } from "../../types.js";

export function renderValuesYaml({
  pools,
  buildId,
  nextVersion,
  config,
  imageRegistry,
}: {
  pools: Map<string, PoolDefinition>;
  buildId: string;
  nextVersion: string;
  config: K8sAdapterConfig;
  imageRegistry: string;
}): string {
  // Output as JSON (valid YAML) with a comment header.
  const gke = "gke" in config.provider ? config.provider.gke : undefined;

  const values = {
    global: {
      image: {
        registry: imageRegistry,
        repository: 'nextjs-app',
        tag: buildId,
        pullPolicy: 'IfNotPresent',
      },
    },
    pools: Object.fromEntries(
      [...pools.entries()].map(([name, pool]) => [
        name,
        {
          replicas: pool.config.scaling ?? { min: 1, max: 3, targetCPU: 80 },
          resources: pool.config.resources ?? {
            requests: { cpu: "250m", memory: "256Mi" },
            limits: { cpu: "1", memory: "512Mi" },
          },
          _meta: { outputCount: pool.outputs.length },
        },
      ]),
    ),
    gateway: gke?.gateway ?? {},
    build: {
      id: buildId,
      nextVersion,
      containerStrategy: config.containerStrategy ?? "traced-assets",
    },
  };

  const header = `# Auto-generated by @next-community/adapter-k8s (provider: gke)\n# Build ID: ${buildId}\n# Next.js: ${nextVersion}\n# Generated: ${new Date().toISOString()}\n`;
  return header + JSON.stringify(values, null, 2);
}
