// src/emit/templates/values-yaml.ts
import type { K8sAdapterConfig, PoolDefinition } from "../../types.js";
import {
  sanitizeK8sName,
  assertSafeBuildId,
  assertSafeImageRegistry,
  assertSafePoolName,
  assertSafeQuantity,
  assertSafeReplicaCount,
  assertSafeTargetCPU,
  UNCONFIGURED_IMAGE_REGISTRY,
} from "./utils.js";
import { POOL_READINESS_PATH } from "./deployment.js";

/**
 * Pool defaults. Exported so the tests (and deploy's per-build snapshot) can pin the
 * exact strings a chart renders when `next.config` says nothing.
 */
export const DEFAULT_POOL_RESOURCES = {
  cpu: "250m",
  memory: "256Mi",
  cpuLimit: "1",
  memoryLimit: "512Mi",
} as const;

export const DEFAULT_POOL_SCALING = { min: 1, max: 3, targetCPU: 80 } as const;

export function renderValuesYaml({
  pools,
  buildId,
  nextVersion,
  config,
  imageRegistry,
}: {
  pools: Map<string, PoolDefinition>;
  buildId: string;
  nextVersion: string;
  config: K8sAdapterConfig;
  imageRegistry: string;
}): string {
  // Output as JSON (valid YAML) with a comment header.
  const gke = "gke" in config.provider ? config.provider.gke : undefined;

  // Sanitize at the point of consumption (AGENTS.md): every value below is read straight
  // out of `next.config`/the build and lands in helm values that the templates splice into
  // rendered YAML with no escaping of their own.
  assertSafeBuildId(buildId);
  // See UNCONFIGURED_IMAGE_REGISTRY: adapter.ts's own "not configured yet" literal, which
  // deploy replaces via `--set`. Exempted by identity so the guard stays strict for every
  // real value.
  if (imageRegistry !== UNCONFIGURED_IMAGE_REGISTRY) assertSafeImageRegistry(imageRegistry);

  const values = {
    global: {
      image: {
        registry: imageRegistry,
        repository: "nextjs-app",
        tag: buildId,
      },
      // Empty by default: the deploy CLI passes `--set global.networkPolicy.podCidrs=
      // {..}` when it can discover the cluster's pod CIDRs; an empty list renders no
      // NetworkPolicies (the templates are wrapped in a helm `if` guard).
      networkPolicy: {
        podCidrs: [] as string[],
      },
    },
    pools: Object.fromEntries(
      [...pools.entries()].map(([name, pool]) => {
        assertSafePoolName(name);
        // N60 (SECURITY). helm performs NO escaping, so these strings reach the pod spec
        // verbatim through `{{ (index .Values.pools "<p>").resources… }}` in
        // deployment.ts. VERIFIED before this guard existed: a memoryLimit of
        // `512Mi"\n      hostNetwork: true\n      shareProcessNamespace: true\n  _pad: "`
        // rendered valid YAML with `hostNetwork: true` on the POD, which voids both
        // NetworkPolicy postures (N19 in network-policy.ts). Same story for the scaling
        // numbers, which hpa.ts interpolates as bare `minReplicas: {{ … }}` scalars.
        const resources = {
          cpu: pool.config.resources?.cpu ?? DEFAULT_POOL_RESOURCES.cpu,
          memory: pool.config.resources?.memory ?? DEFAULT_POOL_RESOURCES.memory,
          cpuLimit: pool.config.resources?.cpuLimit ?? DEFAULT_POOL_RESOURCES.cpuLimit,
          memoryLimit: pool.config.resources?.memoryLimit ?? DEFAULT_POOL_RESOURCES.memoryLimit,
        };
        assertSafeQuantity(resources.cpu, `pool "${name}" resources.cpu`);
        assertSafeQuantity(resources.memory, `pool "${name}" resources.memory`);
        assertSafeQuantity(resources.cpuLimit, `pool "${name}" resources.cpuLimit`);
        assertSafeQuantity(resources.memoryLimit, `pool "${name}" resources.memoryLimit`);

        const scaling = {
          min: pool.config.scaling?.min ?? DEFAULT_POOL_SCALING.min,
          max: pool.config.scaling?.max ?? DEFAULT_POOL_SCALING.max,
          targetCPU: pool.config.scaling?.targetCPU ?? DEFAULT_POOL_SCALING.targetCPU,
        };
        assertSafeReplicaCount(scaling.min, `pool "${name}" scaling.min`);
        assertSafeReplicaCount(scaling.max, `pool "${name}" scaling.max`);
        assertSafeTargetCPU(scaling.targetCPU, `pool "${name}" scaling.targetCPU`);

        return [
          name,
          {
            image: {
              repository:
                config.containerStrategy === "shared-image" ? "nextjs-app" : `nextjs-app-${name}`,
              // S7. Empty by default and filled in by `deploy` with `--set
              // pools.<pool>.image.digest=sha256:…` once `docker push` has RESOLVED it — the
              // chart is generated by `next build`, which runs before the push, so the digest
              // cannot be known at render time. Declared here so the key always exists and the
              // template's `{{ with … }}` never indexes a missing map.
              digest: "",
            },
            replicas: scaling,
            resources: {
              requests: { cpu: resources.cpu, memory: resources.memory },
              limits: { cpu: resources.cpuLimit, memory: resources.memoryLimit },
            },
            _meta: { outputCount: pool.outputs.length },
          },
        ];
      }),
    ),
    // S7: the routing image takes its digest the same way (`--set
    // routingService.image.digest=…`).
    routingService: { image: { digest: "" } },
    gateway: gke?.gateway ?? {},
    build: {
      id: buildId,
      nextVersion,
      containerStrategy: config.containerStrategy ?? "traced-assets",
    },
    activeBuildId: sanitizeK8sName(buildId),
    // The path the LOAD BALANCER's HealthCheckPolicy probes on pool backends. Defaults to
    // readiness; `deploy` overrides it to the liveness path for one cycle when the outgoing
    // build may predate /readyz (see AdapterState.readinessPathSupported).
    poolHealthCheckPath: POOL_READINESS_PATH,
  };

  // N68. NO wall-clock stamp here. The header used to carry
  // `# Generated: ${new Date().toISOString()}`, which made two renders of the SAME build
  // byte-different and defeated the only practical audit of invariant 5 ("clean chart
  // regeneration"): diff a regenerated chart against what was applied. Every other
  // build-time timestamp in the repo goes through manifest.ts's stableBuiltAt()
  // (SOURCE_DATE_EPOCH -> .next/BUILD_ID mtime -> now); this line had no such source and
  // no consumer, so it is simply gone rather than plumbed. Don't reintroduce it.
  const header =
    `# Auto-generated by @next-community/adapter-k8s (provider: gke)\n` +
    `# Build ID: ${buildId}\n` +
    `# Next.js: ${nextVersion}\n`;
  return header + JSON.stringify(values, null, 2);
}
