#!/usr/bin/env bash
set -euo pipefail

# Next.js Adapter E2E Deploy Script — Kubernetes topology.
#
# This is shared by local k3d and configured external clusters. The selected target decides
# the exposure and routing path; both exercise deployed routing, pools, and shared cache.
#
# STRICTLY SERIAL. Every suite deploys to the SAME release on the SAME hostname, so two
# concurrent deploys would race the same blue/green cutover and each would serve the
# other's app. The run wrapper forces -c 1; the lock below is the backstop for anyone
# who invokes this directly.
#
# Deploy target state (adapter.config.mjs + infrastructure.json + state.json + the
# dispatch secret) lives OUTSIDE the harness's temp app, because the harness creates a
# fresh directory per suite and deletes it afterwards. state.json in particular has to
# survive: it carries previousBuildId, which is what makes cutover and rollback mean
# anything. Seed the directory with e2e-cluster.sh.
#
# Contract (from nextjs.org/docs/.../adapterPath#testing-adapters):
# - cwd is set to the isolated test app by the harness
# - Exit non-zero on failure
# - Print deployment URL to stdout (nothing else)
# - Write diagnostics to stderr or files

ADAPTER_DIR="${ADAPTER_DIR:?ADAPTER_DIR must be set}"
CLUSTER_STATE_DIR="${ADAPTER_K8S_E2E_CLUSTER_STATE:?ADAPTER_K8S_E2E_CLUSTER_STATE must be set (run via scripts/e2e-cluster.sh)}"
CLUSTER_LOCK_DIR="${CLUSTER_STATE_DIR}/.deploy.lock"
APP_DIR="$PWD"
E2E_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./e2e-lock.sh
source "${E2E_SCRIPT_DIR}/e2e-lock.sh"

if [ ! -f "${CLUSTER_STATE_DIR}/adapter.config.mjs" ]; then
  echo "[adapter-k8s] Missing ${CLUSTER_STATE_DIR}/adapter.config.mjs" >&2
  exit 1
fi
if [ ! -f "${CLUSTER_STATE_DIR}/.k8s-adapter/infrastructure.json" ]; then
  echo "[adapter-k8s] Missing ${CLUSTER_STATE_DIR}/.k8s-adapter/infrastructure.json" >&2
  exit 1
fi

# --- 0. Serialize against the shared release ---
# Held for the whole deploy, not just the cutover: the build writes into the shared
# state dir too. Waits up to 90 minutes because the queue is one full build+push+rollout
# per waiting suite, and a slow suite ahead is normal rather than a hang.
cluster_lock_acquired=0
if ! e2e_lock_acquire "$CLUSTER_LOCK_DIR" 5400 60; then
  echo "[adapter-k8s] Timed out waiting for the cluster deploy lock: ${CLUSTER_LOCK_DIR}" >&2
  exit 1
fi
cluster_lock_acquired=1

release_cluster_lock() {
  if [ "$cluster_lock_acquired" -eq 1 ]; then
    e2e_lock_release "$CLUSTER_LOCK_DIR"
    cluster_lock_acquired=0
  fi
}
trap release_cluster_lock EXIT

# --- 1. Stage the deploy target into the temp app, BEFORE the build ---
# adapter.config.mjs is read by the adapter during `next build` (createK8sAdapter's
# ensureConfig), so it has to be in place before e2e-setup-common.sh builds — which is
# why this runs above the source line rather than below it.
# The suite's own `nextTestSetup({ env })` values, recovered by diffing against the baseline
# the wrapper snapshotted. 62 of 1,051 e2e suites need these; without them the app deploys
# with no runtime environment and the assertions read `undefined`.
SUITE_ENV_JSON='{}'
if [ -n "${ADAPTER_K8S_E2E_ENV_SNAPSHOT:-}" ] && [ -f "${ADAPTER_K8S_E2E_ENV_SNAPSHOT}" ]; then
  SUITE_ENV_JSON="$(node "$(dirname "${BASH_SOURCE[0]}")/e2e-cluster-env.mjs" \
    "${ADAPTER_K8S_E2E_ENV_SNAPSHOT}")"
fi

# Layer that env onto the deploy target's config without editing the seeded file: keep the
# original as the base and generate a wrapper that spreads its `.config` and adds `env`.
# (createK8sAdapter's return exposes `.config`; the adapter's loader accepts a plain object.)
cp "${CLUSTER_STATE_DIR}/adapter.config.mjs" "${APP_DIR}/adapter.config.base.mjs"
cat > "${APP_DIR}/adapter.config.mjs" <<EOF
// GENERATED by scripts/e2e-cluster-deploy.sh — do not edit.
import base from "./adapter.config.base.mjs";
const cfg = base?.config ?? base;
export default {
  ...cfg,
  env: { ...(cfg.env ?? {}), ...${SUITE_ENV_JSON} },
};
EOF
mkdir -p "${APP_DIR}/.k8s-adapter"
cp "${CLUSTER_STATE_DIR}/.k8s-adapter/infrastructure.json" "${APP_DIR}/.k8s-adapter/"
for optional in internal-secret.key state.json; do
  if [ -f "${CLUSTER_STATE_DIR}/.k8s-adapter/${optional}" ]; then
    cp "${CLUSTER_STATE_DIR}/.k8s-adapter/${optional}" "${APP_DIR}/.k8s-adapter/"
  fi
done
chmod 600 "${APP_DIR}/.k8s-adapter/internal-secret.key" 2>/dev/null || true

# The pool topologies skip container staging; this one needs the staged context to
# build an image from. Must be set before sourcing common, which defaults it to 1.
export ADAPTER_K8S_SKIP_STAGING=0

# deploymentId is ON for cluster runs again: Next still pins its BUILD_ID to a literal
# constant in deploymentId mode, but the adapter now substitutes the (unique-per-deploy)
# deploymentId as its effective build id (effectiveBuildId, src/adapter.ts), so blue/green
# names, image tags, and the Valkey namespace stay unique. Suites that assert `?dpl=` asset
# URLs, worker NEXT_DEPLOYMENT_ID, and skew headers need the id end-to-end — and the
# deployment-skew fixtures refuse to BUILD without one.

# --- 2. Shared setup: pack adapter, install, build ---
# shellcheck source=./e2e-setup-common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/e2e-setup-common.sh"

# e2e-setup-common.sh installs its own EXIT trap (diagnostics). Re-register ours on top
# so the lock is still released — bash replaces rather than chains traps, so the common
# handler is called explicitly here.
cluster_on_exit() {
  # on_exit FIRST: it reads $?, which is only the script's real exit status before any
  # other command runs in this handler.
  on_exit
  release_cluster_lock
}
trap cluster_on_exit EXIT

# --- 3. Deploy to the cluster ---
# --skip-build: e2e-setup-common.sh already ran the app build with the adapter attached,
# so .k8s-adapter/output is current. Rebuilding here would discard the harness's build
# env (NEXT_DEPLOYMENT_ID, the cache-components bridge) and mint a different build id
# than the DEPLOYMENT_ID marker the suite asserts against.
# --yes: no TTY, and the kubectl context is pinned by the wrapper.
#
# The CLI comes from the INSTALLED package, matching the pool/routing tiers: the suite
# should exercise the packed artifact, so a missing `files` entry fails here too.
CLI_CJS="${ADAPTER_INSTALL_DIR}/dist/cli.cjs"
[ -f "$CLI_CJS" ] || CLI_CJS="${ADAPTER_DIR}/dist/cli.cjs"
echo "[adapter-k8s] Deploying to cluster via ${CLI_CJS}..." >&2
DEPLOY_START=$(date +%s)
(
  cd "$APP_DIR"
  node "$CLI_CJS" deploy --skip-build --yes
) >&2
echo "[adapter-k8s] Deploy took $(( $(date +%s) - DEPLOY_START ))s" >&2

# --- 4. Persist state back to the shared dir ---
# state.json advanced (buildId -> previousBuildId, new cdn tag, new routing digest).
# Losing it would break the NEXT suite's cutover, not this one's, which is exactly the
# kind of failure that gets blamed on the wrong test.
cp "${APP_DIR}/.k8s-adapter/state.json" "${CLUSTER_STATE_DIR}/.k8s-adapter/state.json"
if [ -f "${APP_DIR}/.k8s-adapter/internal-secret.key" ]; then
  cp "${APP_DIR}/.k8s-adapter/internal-secret.key" "${CLUSTER_STATE_DIR}/.k8s-adapter/"
fi

# --- 5. Wait for the public path to actually serve this build ---
# `deploy` returns when the rollout is complete in-cluster, which can still be upstream of
# the selected exposure's data plane or CDN. Polling the public host proves that path is live;
# without it the first assertions race the edge and fail as "adapter bugs".
HOST="$(node -e "
const j = require('${APP_DIR}/.k8s-adapter/infrastructure.json');
process.stdout.write(j.hosts[0]);
")"
# External targets serve on https://<host> by default; local k3d uses a mapped port
# over plain HTTP (http://<host>.localhost:<port>). The wrapper that knows the topology
# exports the base URL; the hostname-derived HTTPS form stays the default for cloud runs.
URL="${ADAPTER_K8S_E2E_BASE_URL:-https://${HOST}}"

# LOCAL topology only: before trusting any HTTP probe, require the release's HTTPRoute to be
# Accepted by the gateway controller. The curl gate deliberately tolerates 404 (an app may
# 404 at /), which made it blind to the one local failure mode that matters: a route whose
# listener never attached (measured: merged-gateway listener conflicts 404'd every request
# and the gate waved it through; 40+ suites then failed on empty bodies).
if [ -n "${ADAPTER_K8S_E2E_BASE_URL:-}" ]; then
  RELEASE_NAME_JSON="$(node -e "
    process.stdout.write(require('${APP_DIR}/.k8s-adapter/infrastructure.json').releaseName);
  ")"
  ROUTE_OK=0
  for _i in $(seq 1 30); do
    ACCEPTED="$(kubectl get httproute "${RELEASE_NAME_JSON}-routes"       -o jsonpath='{.status.parents[0].conditions[?(@.type=="Accepted")].status}' 2>/dev/null || true)"
    [ "$ACCEPTED" = "True" ] && { ROUTE_OK=1; break; }
    sleep 2
  done
  if [ "$ROUTE_OK" -ne 1 ]; then
    MSG="$(kubectl get httproute "${RELEASE_NAME_JSON}-routes"       -o jsonpath='{.status.parents[0].conditions[?(@.type=="Accepted")].message}' 2>/dev/null || true)"
    echo "[adapter-k8s] HTTPRoute ${RELEASE_NAME_JSON}-routes is NOT Accepted: ${MSG:-no status}" >&2
    exit 1
  fi
fi
# Require a RUN of consecutive good responses, not one. `deploy` returns once the new
# rollout is complete, but the previous build's pods are still draining and the routing
# service is still rolling — measured on this cluster, requests in that window return 503
# from the LB with no healthy backend. A single-probe gate let the suite start inside it,
# and the resulting failures (a 404 assertion seeing 503, a client navigation timing out)
# read exactly like adapter bugs. Any stability gate is a heuristic; this one costs ~16s
# per deploy and converts a whole class of phantom failures into wall-clock.
STABLE_REQUIRED=8
stable=0
for i in $(seq 1 90); do
  code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 "${URL}/" || echo 000)"
  # Any answered status means the edge is routing to this release; the fixture itself
  # may legitimately 404 at / (plenty of upstream apps have no index route).
  case "$code" in
    000 | 502 | 503 | 504) stable=0 ;;
    *) stable=$((stable + 1)) ;;
  esac
  if [ "$stable" -ge "$STABLE_REQUIRED" ]; then
    echo "[adapter-k8s] Public path stable (${code} × ${stable}) after ${i} poll(s)" >&2
    break
  fi
  if [ "$i" -eq 90 ]; then
    echo "[adapter-k8s] TIMEOUT — ${URL}/ never held steady (last ${code}, run ${stable})" >&2
    exit 1
  fi
  sleep 2
done

# --- 6. URL on stdout ---
echo "$URL"
