#!/usr/bin/env bash
set -euo pipefail

# Next.js Adapter E2E Deploy Script — PHASE 3 topology (REAL CLUSTER).
#
# Unlike the other two topologies, this one puts the upstream test app behind the
# production request path: GXLB -> Cloud CDN -> ext_proc routing service -> pool.
# That is the whole point — it is the only way to see CDN interaction, GCP-programmed
# match conditions, and multi-replica cache state, none of which any local topology has.
#
#   scripts/e2e-deploy.sh              Phase 1: pool server only        (local)
#   scripts/e2e-integration-deploy.sh  Phase 2: Envoy -> ext_proc -> pool (local)
#   scripts/e2e-cluster-deploy.sh      Phase 3: real cluster             (this file)
#
# STRICTLY SERIAL. Every suite deploys to the SAME release on the SAME hostname, so two
# concurrent deploys would race the same blue/green cutover and each would serve the
# other's app. The run wrapper forces -c 1; the lock below is the backstop for anyone
# who invokes this directly.
#
# Deploy target state (adapter.config.mjs + infrastructure.json + state.json + the
# dispatch secret) lives OUTSIDE the harness's temp app, because the harness creates a
# fresh directory per suite and deletes it afterwards. state.json in particular has to
# survive: it carries previousBuildId, which is what makes cutover and rollback mean
# anything. Seed the directory with e2e-cluster.sh.
#
# Contract (from nextjs.org/docs/.../adapterPath#testing-adapters):
# - cwd is set to the isolated test app by the harness
# - Exit non-zero on failure
# - Print deployment URL to stdout (nothing else)
# - Write diagnostics to stderr or files

ADAPTER_DIR="${ADAPTER_DIR:?ADAPTER_DIR must be set}"
CLUSTER_STATE_DIR="${ADAPTER_K8S_E2E_CLUSTER_STATE:?ADAPTER_K8S_E2E_CLUSTER_STATE must be set (run via scripts/e2e-cluster.sh)}"
CLUSTER_LOCK_DIR="${CLUSTER_STATE_DIR}/.deploy.lock"
APP_DIR="$PWD"

if [ ! -f "${CLUSTER_STATE_DIR}/adapter.config.mjs" ]; then
  echo "[adapter-k8s] Missing ${CLUSTER_STATE_DIR}/adapter.config.mjs" >&2
  exit 1
fi
if [ ! -f "${CLUSTER_STATE_DIR}/.k8s-adapter/infrastructure.json" ]; then
  echo "[adapter-k8s] Missing ${CLUSTER_STATE_DIR}/.k8s-adapter/infrastructure.json" >&2
  exit 1
fi

# --- 0. Serialize against the shared release ---
# Held for the whole deploy, not just the cutover: the build writes into the shared
# state dir too. Waits up to 90 minutes because the queue is one full build+push+rollout
# per waiting suite, and a slow suite ahead is normal rather than a hang.
cluster_lock_acquired=0
for _attempt in $(seq 1 54000); do
  if mkdir "$CLUSTER_LOCK_DIR" 2>/dev/null; then
    printf '%s\n' "$$" > "${CLUSTER_LOCK_DIR}/owner"
    cluster_lock_acquired=1
    break
  fi
  lock_owner="$(cat "${CLUSTER_LOCK_DIR}/owner" 2>/dev/null || true)"
  if [[ "$lock_owner" =~ ^[0-9]+$ ]] && ! kill -0 "$lock_owner" 2>/dev/null; then
    stale="${CLUSTER_LOCK_DIR}.stale.$$.$_attempt"
    if mv "$CLUSTER_LOCK_DIR" "$stale" 2>/dev/null; then rm -rf "$stale"; fi
  fi
  sleep 0.1
done
if [ "$cluster_lock_acquired" -ne 1 ]; then
  echo "[adapter-k8s] Timed out waiting for the cluster deploy lock: ${CLUSTER_LOCK_DIR}" >&2
  exit 1
fi

release_cluster_lock() {
  if [ "$cluster_lock_acquired" -eq 1 ]; then
    rm -f "${CLUSTER_LOCK_DIR}/owner"
    rmdir "$CLUSTER_LOCK_DIR" 2>/dev/null || true
    cluster_lock_acquired=0
  fi
}
trap release_cluster_lock EXIT

# --- 1. Stage the deploy target into the temp app, BEFORE the build ---
# adapter.config.mjs is read by the adapter during `next build` (createK8sAdapter's
# ensureConfig), so it has to be in place before e2e-setup-common.sh builds — which is
# why this runs above the source line rather than below it.
# The suite's own `nextTestSetup({ env })` values, recovered by diffing against the baseline
# the wrapper snapshotted. 62 of 1,051 e2e suites need these; without them the app deploys
# with no runtime environment and the assertions read `undefined`.
SUITE_ENV_JSON='{}'
if [ -n "${ADAPTER_K8S_E2E_ENV_SNAPSHOT:-}" ] && [ -f "${ADAPTER_K8S_E2E_ENV_SNAPSHOT}" ]; then
  SUITE_ENV_JSON="$(node "$(dirname "${BASH_SOURCE[0]}")/e2e-cluster-env.mjs" \
    "${ADAPTER_K8S_E2E_ENV_SNAPSHOT}")"
fi

# Layer that env onto the deploy target's config without editing the seeded file: keep the
# original as the base and generate a wrapper that spreads its `.config` and adds `env`.
# (createK8sAdapter's return exposes `.config`; the adapter's loader accepts a plain object.)
cp "${CLUSTER_STATE_DIR}/adapter.config.mjs" "${APP_DIR}/adapter.config.base.mjs"
cat > "${APP_DIR}/adapter.config.mjs" <<EOF
// GENERATED by scripts/e2e-cluster-deploy.sh — do not edit.
import base from "./adapter.config.base.mjs";
const cfg = base?.config ?? base;
export default {
  ...cfg,
  env: { ...(cfg.env ?? {}), ...${SUITE_ENV_JSON} },
};
EOF
mkdir -p "${APP_DIR}/.k8s-adapter"
cp "${CLUSTER_STATE_DIR}/.k8s-adapter/infrastructure.json" "${APP_DIR}/.k8s-adapter/"
for optional in internal-secret.key state.json; do
  if [ -f "${CLUSTER_STATE_DIR}/.k8s-adapter/${optional}" ]; then
    cp "${CLUSTER_STATE_DIR}/.k8s-adapter/${optional}" "${APP_DIR}/.k8s-adapter/"
  fi
done
chmod 600 "${APP_DIR}/.k8s-adapter/internal-secret.key" 2>/dev/null || true

# The pool topologies skip container staging; this one needs the staged context to
# build an image from. Must be set before sourcing common, which defaults it to 1.
export ADAPTER_K8S_SKIP_STAGING=0

# No deploymentId on a real cluster — it pins Next's build id to a literal constant, which
# collapses blue/green across every suite. See the long note in e2e-setup-common.sh.
export ADAPTER_K8S_SET_DEPLOYMENT_ID=0

# --- 2. Shared setup: pack adapter, install, build ---
# shellcheck source=./e2e-setup-common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/e2e-setup-common.sh"

# e2e-setup-common.sh installs its own EXIT trap (diagnostics). Re-register ours on top
# so the lock is still released — bash replaces rather than chains traps, so the common
# handler is called explicitly here.
cluster_on_exit() {
  # on_exit FIRST: it reads $?, which is only the script's real exit status before any
  # other command runs in this handler.
  on_exit
  release_cluster_lock
}
trap cluster_on_exit EXIT

# --- 3. Deploy to the cluster ---
# --skip-build: e2e-setup-common.sh already ran the app build with the adapter attached,
# so .k8s-adapter/output is current. Rebuilding here would discard the harness's build
# env (NEXT_DEPLOYMENT_ID, the cache-components bridge) and mint a different build id
# than the DEPLOYMENT_ID marker the suite asserts against.
# --yes: no TTY, and the kubectl context is pinned by the wrapper.
#
# The CLI comes from the INSTALLED package, matching the pool/routing tiers: the suite
# should exercise the packed artifact, so a missing `files` entry fails here too.
CLI_CJS="${ADAPTER_INSTALL_DIR}/dist/cli.cjs"
[ -f "$CLI_CJS" ] || CLI_CJS="${ADAPTER_DIR}/dist/cli.cjs"
echo "[adapter-k8s] Deploying to cluster via ${CLI_CJS}..." >&2
DEPLOY_START=$(date +%s)
(
  cd "$APP_DIR"
  node "$CLI_CJS" deploy --skip-build --yes
) >&2
echo "[adapter-k8s] Deploy took $(( $(date +%s) - DEPLOY_START ))s" >&2

# --- 4. Persist state back to the shared dir ---
# state.json advanced (buildId -> previousBuildId, new cdn tag, new routing digest).
# Losing it would break the NEXT suite's cutover, not this one's, which is exactly the
# kind of failure that gets blamed on the wrong test.
cp "${APP_DIR}/.k8s-adapter/state.json" "${CLUSTER_STATE_DIR}/.k8s-adapter/state.json"
if [ -f "${APP_DIR}/.k8s-adapter/internal-secret.key" ]; then
  cp "${APP_DIR}/.k8s-adapter/internal-secret.key" "${CLUSTER_STATE_DIR}/.k8s-adapter/"
fi

# --- 5. Wait for the public path to actually serve this build ---
# `deploy` returns when the rollout is complete in-cluster, which is upstream of the
# GXLB/CDN. Polling the public host is what proves the request path is live; without it
# the first assertions of the suite race the load balancer and fail as "adapter bugs".
HOST="$(node -e "
const j = require('${APP_DIR}/.k8s-adapter/infrastructure.json');
process.stdout.write(j.hosts[0]);
")"
URL="https://${HOST}"
# Require a RUN of consecutive good responses, not one. `deploy` returns once the new
# rollout is complete, but the previous build's pods are still draining and the routing
# service is still rolling — measured on this cluster, requests in that window return 503
# from the LB with no healthy backend. A single-probe gate let the suite start inside it,
# and the resulting failures (a 404 assertion seeing 503, a client navigation timing out)
# read exactly like adapter bugs. Any stability gate is a heuristic; this one costs ~16s
# per deploy and converts a whole class of phantom failures into wall-clock.
STABLE_REQUIRED=8
stable=0
for i in $(seq 1 90); do
  code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 "${URL}/" || echo 000)"
  # Any answered status means the edge is routing to this release; the fixture itself
  # may legitimately 404 at / (plenty of upstream apps have no index route).
  case "$code" in
    000 | 502 | 503 | 504) stable=0 ;;
    *) stable=$((stable + 1)) ;;
  esac
  if [ "$stable" -ge "$STABLE_REQUIRED" ]; then
    echo "[adapter-k8s] Public path stable (${code} × ${stable}) after ${i} poll(s)" >&2
    break
  fi
  if [ "$i" -eq 90 ]; then
    echo "[adapter-k8s] TIMEOUT — ${URL}/ never held steady (last ${code}, run ${stable})" >&2
    exit 1
  fi
  sleep 2
done

# --- 6. URL on stdout ---
echo "$URL"
